### ISSUE TITLE
[1.20.1] Conflict with CC: Tweaked mod

### ISSUE THREAD

**Issue by stdcall0** [Fabricators-of-Create/Create#1029]
### Describe the Bug

Crash with both two mods installed.

Error log:
```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'create'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.21.jar:?]
        at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.14.21-launcher.0.11.2.jar:0.11.2]
Caused by: java.lang.NoClassDefFoundError: dan200/computercraft/api/peripheral/IPeripheralProvider
        at com.simibubi.create.compat.computercraft.implementation.ComputerBehaviour.<clinit>(ComputerBehaviour.java:25) ~[create-fabric-0.5.1-d-build.1115+mc1.20.1-ccfixz.jar:?]
        at com.simibubi.create.compat.computercraft.ComputerCraftProxy.registerWithDependency(ComputerCraftProxy.java:22) ~[create-fabric-0.5.1-d-build.1115+mc1.20.1-ccfixz.jar:?]
        at com.simibubi.create.compat.Mods.executeIfInstalled(Mods.java:71) ~[create-fabric-0.5.1-d-build.1115+mc1.20.1-ccfixz.jar:?]
        at com.simibubi.create.compat.computercraft.ComputerCraftProxy.register(ComputerCraftProxy.java:15) ~[create-fabric-0.5.1-d-build.1115+mc1.20.1-ccfixz.jar:?]
        at com.simibubi.create.Create.onInitialize(Create.java:135) ~[create-fabric-0.5.1-d-build.1115+mc1.20.1-ccfixz.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
        ... 8 more
Caused by: java.lang.ClassNotFoundException: dan200.computercraft.api.peripheral.IPeripheralProvider
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at com.simibubi.create.compat.computercraft.implementation.ComputerBehaviour.<clinit>(ComputerBehaviour.java:25) ~[create-fabric-0.5.1-d-build.1115+mc1.20.1-ccfixz.jar:?]
        at com.simibubi.create.compat.computercraft.ComputerCraftProxy.registerWithDependency(ComputerCraftProxy.java:22) ~[create-fabric-0.5.1-d-build.1115+mc1.20.1-ccfixz.jar:?]
        at com.simibubi.create.compat.Mods.executeIfInstalled(Mods.java:71) ~[create-fabric-0.5.1-d-build.1115+mc1.20.1-ccfixz.jar:?]
        at com.simibubi.create.compat.computercraft.ComputerCraftProxy.register(ComputerCraftProxy.java:15) ~[create-fabric-0.5.1-d-build.1115+mc1.20.1-ccfixz.jar:?]
        at com.simibubi.create.Create.onInitialize(Create.java:135) ~[create-fabric-0.5.1-d-build.1115+mc1.20.1-ccfixz.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
        ... 8 more
```

### Reproduction Steps

Get the latest fabric versions of create, fabric-api and cc:tweaked
And start the game

(cc-tweaked-1.20.1-fabric-1.106.1.jar
fabric-api-0.86.1+1.20.1.jar
create-fabric-0.5.1-d-build.1115+mc1.20.1.jar)

### Expected Result

It should work!

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Additional Context

I found out that the interface `IPeripheralProvider` is only for Forge version of CC:Tweaked ([here](https://github.com/cc-tweaked/CC-Tweaked/tree/41b6711b38efef5686ff3df4d6f9597ddfab7164/projects/forge-api/src/main/java/dan200/computercraft/api/peripheral))

**Comment by TropheusJ** [comment]
fixed by #1009
