### ISSUE TITLE
Crash with minecraft 1.20.1

### ISSUE THREAD

**Issue by l741589** [Fabricators-of-Create/Create#1074]
### Describe the Bug

crash with minecraft 1.20.1

log:
```
java.lang.IllegalStateException: Missing registry: ResourceKey[minecraft:root / minecraft:dimension_type]
	at net.minecraft.class_5455.method_30534(class_5455.java:26) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_5455.method_30530(class_5455.java:26) ~[client-intermediary.jar:?]
	at com.simibubi.create.foundation.utility.WorldHelper.getDimensionID(WorldHelper.java:10) ~[%5B机械动力%5D%20create-fabric-0.5.1-d-build.1161+mc1.20.1.jar:?]
	at com.simibubi.create.content.redstone.link.RedstoneLinkNetworkHandler.onLoadWorld(RedstoneLinkNetworkHandler.java:71) ~[%5B机械动力%5D%20create-fabric-0.5.1-d-build.1161+mc1.20.1.jar:?]
	at com.simibubi.create.foundation.events.CommonEvents.onLoadWorld(CommonEvents.java:170) ~[%5B机械动力%5D%20create-fabric-0.5.1-d-build.1161+mc1.20.1.jar:?]
	at io.github.fabricators_of_create.porting_lib.event.client.ClientWorldEvents.lambda$static$0(ClientWorldEvents.java:14) ~[porting_lib_base-2.1.1127+1.20-ea6282156cba7170.jar:?]
	at net.minecraft.class_638.handler$zea000$porting_lib_base$port_lib$init(class_638.java:2121) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.<init>(class_638.java:180) ~[client-intermediary.jar:?]
	at nl.enjarai.showmeyourskin.client.cursed.DummyClientWorld.<init>(DummyClientWorld.java:26) ~[show-me-your-skin-1.6.9+1.20.jar:?]
	at nl.enjarai.showmeyourskin.client.cursed.DummyClientWorld.getInstance(DummyClientWorld.java:21) ~[show-me-your-skin-1.6.9+1.20.jar:?]
	at nl.enjarai.showmeyourskin.client.cursed.DummyClientPlayerEntity.<init>(DummyClientPlayerEntity.java:46) ~[show-me-your-skin-1.6.9+1.20.jar:?]
	at nl.enjarai.showmeyourskin.client.cursed.DummyClientPlayerEntity$1.<init>(DummyClientPlayerEntity.java:36) ~[show-me-your-skin-1.6.9+1.20.jar:?]
	at nl.enjarai.showmeyourskin.client.cursed.DummyClientPlayerEntity.getInstance(DummyClientPlayerEntity.java:36) ~[show-me-your-skin-1.6.9+1.20.jar:?]
	at nl.enjarai.showmeyourskin.ShowMeYourSkinClient.lambda$onInitializeClient$1(ShowMeYourSkinClient.java:42) ~[show-me-your-skin-1.6.9+1.20.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientLifecycleEvents.lambda$static$0(ClientLifecycleEvents.java:35) ~[fabric-lifecycle-events-v1-2.2.2+b3afc78b77-21c1963f26916f23.jar:?]
	at net.minecraft.class_310.handler$bme000$fabric-lifecycle-events-v1$onStart(class_310.java:9033) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:781) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-Fabric%200.14.22.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:53) ~[?:?]
```

### Reproduction Steps

-

### Expected Result

-

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

architectury-9.1.10-fabric.jar
carpetskyadditions-1.20.1-4.4.0.jar
cloth-config-11.1.106-fabric.jar
fabric-api-0.87.0+1.20.1.jar
fabric-language-kotlin-1.10.0+kotlin.1.9.0.jar
ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric.jar
LeavesBeGone-v8.0.0-1.20.1-Fabric.jar
libIPN-fabric-1.20-3.0.2.jar
malilib-fabric-1.20.1-0.16.1.jar
PuzzlesLib-v8.0.7-1.20.1-Fabric.jar
show-me-your-skin-1.6.9+1.20.jar
tweakeroo-fabric-1.20.1-0.17.1.jar
fabric-carpet-1.20-1.4.112+v230608.jar
gugle-carpet-addition-2.6.0-1.20.1.jar
RoughlyEnoughItems-12.0.630.jar
XaerosWorldMap_1.30.6_Fabric_1.20.jar
Xaeros_Minimap_23.5.0_Fabric_1.20.jar
InventoryProfilesNext-fabric-1.20-1.10.6.jar
litematica-fabric-1.20.1-0.15.3.jar
create-fabric-0.5.1-d-build.1161+mc1.20.1.jar
Neat-1.20-35-FABRIC.jar
modmenu-7.1.0.jar
invhud.fabric.1.20-3.4.17.jar
itemscroller-fabric-1.20.1-0.20.0.jar
BBOutlineReloaded-2.6-1.20.1-fabric.jar
appleskin-fabric-mc1.20-2.5.0.jar
diggusmaximus-1.5.9-1.20.jar
minihud-fabric-1.20.1-0.27.0.jar
sodium-fabric-mc1.20-0.4.10+build.27.jar
magiclib-all-0.7.346+e235d92-stable.jar

**Comment by l741589** [comment]
I found the problem.
it's not compatible for show-me-your-skin-1.6.9+1.20.jar.
upgrade it to 1.6.11 would fix it
