### ISSUE TITLE
Windmill crashes player

### ISSUE THREAD

**Issue by Steallight** [Fabricators-of-Create/Create#1127]
### Describe the Bug

After building a Windmill the User wanted to start the Windmill the user gets immediately kicked and is softlocked and cannot join the world.

Description: Rendering entity in world

java.lang.IllegalStateException
	at ca.spottedleaf.starlight.common.light.BlockStarLightEngine.initNibble(BlockStarLightEngine.java:78)
	at ca.spottedleaf.starlight.common.light.StarLightEngine.handleEmptySectionChanges(StarLightEngine.java:783)
	at ca.spottedleaf.starlight.common.light.StarLightEngine.blocksChangedInChunk(StarLightEngine.java:422)
	at ca.spottedleaf.starlight.common.light.StarLightInterface.propagateChanges(StarLightInterface.java:552)
	at net.minecraft.class_3568.method_15516(class_3568.java:1599)
	at com.jozufozu.flywheel.core.virtual.VirtualRenderWorld.runLightingEngine(VirtualRenderWorld.java:97)
	at com.simibubi.create.content.contraptions.render.ContraptionRenderDispatcher.setupRenderWorld(ContraptionRenderDispatcher.java:131)
	at com.simibubi.create.content.contraptions.render.FlwContraptionManager.create(FlwContraptionManager.java:84)
	at com.simibubi.create.content.contraptions.render.FlwContraptionManager.create(FlwContraptionManager.java:22)
	at com.simibubi.create.content.contraptions.render.ContraptionRenderingWorld.getRenderInfo(ContraptionRenderingWorld.java:95)
	at com.simibubi.create.content.contraptions.render.ContraptionRenderDispatcher.renderFromEntity(ContraptionRenderDispatcher.java:94)
	at com.simibubi.create.content.contraptions.render.ContraptionEntityRenderer.render(ContraptionEntityRenderer.java:44)
	at com.simibubi.create.content.contraptions.render.ContraptionEntityRenderer.method_3936(ContraptionEntityRenderer.java:13)
	at net.minecraft.class_898.method_3954(class_898.java:145)
	at net.minecraft.class_761.method_22977(class_761.java:1574)
	at net.minecraft.class_761.method_22710(class_761.java:1324)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### Reproduction Steps

1.build the windmill
2.start the windmill
3.
...

### Expected Result

start the Windmill and the player wont be kicked

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/69077005/3b58dfe6-3e78-49df-80f5-9b95220ad4d2)

### Crash Report or Log

https://hastebin.com/share/puruhunole.yaml

### Operating System

Windows 10 & 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

![Screenshot_3](https://github.com/Fabricators-of-Create/Create/assets/69077005/48e578b0-8dad-48c8-a9dc-09627df5ace9)
![Screenshot_4](https://github.com/Fabricators-of-Create/Create/assets/69077005/fc55f4a2-aa4e-437d-971d-2349a202a6b8)
![Screenshot_5](https://github.com/Fabricators-of-Create/Create/assets/69077005/9b37fac7-943a-4cea-8509-b119d22d3250)

### Additional Context

The Crash occured at first on a Server. We removed a specific Mod we thought at first was the fault. Later we found out the Create Fabric Mod was the problem (see the Logs).

**Comment by TropheusJ** [comment]
remove starlight
