### ISSUE TITLE
gantry crashes when putting it on gantry line

### ISSUE THREAD

**Issue by cheesebone** [Fabricators-of-Create/Create#1192]
### Describe the Bug

gantry crashes when putting it on gantry line

### Reproduction Steps

1. set up water wheel
2. connect to line for gantry
3. place gantry itself on top after placing the line
4. game crashes with "Java.lang.IllegalStateException" error

### Expected Result

the gantry to fucking work

### Operating System

windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

﻿

الكا
_bclib_deactivated bclib-3.0.13.jar
better-nether-9.0.9.jar
c2me-fabric-mc1.20.1-0.2.0-alpha.11.0.jar
create-fabric-0.5.1-d-build.1161+mc1.20.1.jar dynamic-fps-3.2.1+minecraft-1.20.0.jar
enhancedblockentities-0.9+1.20.jar
fabric-api-0.90.7+1.20.1.jar
badpackets-fabric-0.4.3.jar better-end-4.0.10.jar
borderless-mining-1.1.8+1.20.1.jar
cloth-config-11.1.106-fabric.jar
cristellib-1.1.3-fabric.jar
emi-1.0.24+1.20.1+fabric.jar
entityculling-fabric-1.6.2-mc1.20.1.jar
fabric-language-kotlin-1.10.13+kotlin.1.9.20.jar
ferritecore-6.0.1-fabric.jar
lithium-fabric-mc1.20.1-0.11.2.jar
farmers-delight-fabric-mc1.20.1-1.4.2.jar
krypton-0.2.3.jar
modernfix-fabric-5.9.2+mc1.20.1.jar
modmenu-7.2.2.jar
morechathistory-1.19.1-1.1.1.jar
NoChatReports-FABRIC-1.20.1-v2.2.2.jar
no-telemetry-1.7.0.jar
raised-fabric-1.20.1-3.1.0.jar
sliceanddice-fabric-3.0.0.jar starlight-1.1.2+fabric.dbc156f.jar
Terralith_1.20.2_v2.4.8.jar
voicechat-fabric-1.20.1-2.4.28.jar
WWOO-FABRIC+FORGE+QUILT-2.0.0.jar
Zoomify-2.11.2.jar
Patchouli-1.20.1-81-FABRIC.jar
Rrls-3.2.0-1.20.1-fabric.jar
sodium-fabric-mc1.20-0.4.10+build.27.jar
Steam_Rails-1.5.1+fabric-mc1.20.1.jar
wthit-fabric-8.4.1.jar
Towns-and-Towers-1.11.1-Fabric+Forge.jar
yet-another-config-lib-fabric-3.2.1+1.20.jar

**Comment by drwoops** [comment]
please attach the crash report

**Comment by cheesebone** [comment]
The game crashed whilst unexpected error
![image_2023-11-12_114047100](https://github.com/Fabricators-of-Create/Create/assets/150570564/b05dcfe2-c623-4101-

Error: java.lang.IllegalStateException
exit code: -1 


---- Minecraft Crash Report ----
// My bad.

Time: 2023-11-12 11:38:18
Description: Unexpected error

java.lang.IllegalStateException
	at ca.spottedleaf.starlight.common.light.BlockStarLightEngine.initNibble(BlockStarLightEngine.java:78)
	at ca.spottedleaf.starlight.common.light.StarLightEngine.handleEmptySectionChanges(StarLightEngine.java:783)
	at ca.spottedleaf.starlight.common.light.StarLightEngine.blocksChangedInChunk(StarLightEngine.java:422)
	at ca.spottedleaf.starlight.common.light.StarLightInterface.propagateChanges(StarLightInterface.java:552)
	at net.minecraft.class_3568.method_15516(class_3568.java:1099)
	at com.jozufozu.flywheel.core.virtual.VirtualRenderWorld.runLightingEngine(VirtualRenderWorld.java:97)
	at com.simibubi.create.content.contraptions.render.ContraptionRenderDispatcher.setupRenderWorld(ContraptionRenderDispatcher.java:131)
	at com.simibubi.create.content.contraptions.render.FlwContraptionManager.create(FlwContraptionManager.java:84)
	at com.simibubi.create.content.contraptions.render.FlwContraptionManager.create(FlwContraptionManager.java:22)
	at com.simibubi.create.content.contraptions.render.ContraptionRenderingWorld.getRenderInfo(ContraptionRenderingWorld.java:95)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at com.simibubi.create.content.contraptions.render.ContraptionRenderingWorld.tick(ContraptionRenderingWorld.java:68)
	at com.simibubi.create.content.contraptions.render.FlwContraptionManager.tick(FlwContraptionManager.java:30)
	at com.simibubi.create.content.contraptions.render.ContraptionRenderDispatcher.tick(ContraptionRenderDispatcher.java:66)
	at com.simibubi.create.foundation.events.ClientEvents.onTick(ClientEvents.java:189)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43)
	at net.minecraft.class_310.handler$bke000$fabric-lifecycle-events-v1$onEndTick(class_310.java:8022)
	at net.minecraft.class_310.method_1574(class_310.java:1957)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at ca.spottedleaf.starlight.common.light.BlockStarLightEngine.initNibble(BlockStarLightEngine.java:78)
	at ca.spottedleaf.starlight.common.light.StarLightEngine.handleEmptySectionChanges(StarLightEngine.java:783)
	at ca.spottedleaf.starlight.common.light.StarLightEngine.blocksChangedInChunk(StarLightEngine.java:422)
	at ca.spottedleaf.starlight.common.light.StarLightInterface.propagateChanges(StarLightInterface.java:552)
	at net.minecraft.class_3568.method_15516(class_3568.java:1099)
	at com.jozufozu.flywheel.core.virtual.VirtualRenderWorld.runLightingEngine(VirtualRenderWorld.java:97)
	at com.simibubi.create.content.contraptions.render.ContraptionRenderDispatcher.setupRenderWorld(ContraptionRenderDispatcher.java:131)
	at com.simibubi.create.content.contraptions.render.FlwContraptionManager.create(FlwContraptionManager.java:84)
	at com.simibubi.create.content.contraptions.render.FlwContraptionManager.create(FlwContraptionManager.java:22)
	at com.simibubi.create.content.contraptions.render.ContraptionRenderingWorld.getRenderInfo(ContraptionRenderingWorld.java:95)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at com.simibubi.create.content.contraptions.render.ContraptionRenderingWorld.tick(ContraptionRenderingWorld.java:68)
	at com.simibubi.create.content.contraptions.render.FlwContraptionManager.tick(FlwContraptionManager.java:30)
	at com.simibubi.create.content.contraptions.render.ContraptionRenderDispatcher.tick(ContraptionRenderDispatcher.java:66)
	at com.simibubi.create.foundation.events.ClientEvents.onTick(ClientEvents.java:189)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43)
	at net.minecraft.class_310.handler$bke000$fabric-lifecycle-events-v1$onEndTick(class_310.java:8022)

-- Affected level --
Details:
	All players: 1 total; [class_746['electricbone1012'/68, l='ClientLevel', x=4249.47, y=68.14, z=-2169.58]]
	Chunk stats: 1024, 145
	Level dimension: minecraft:overworld
	Level spawn location: World: (-48,67,80), Section: (at 0,3,0 in -3,4,5; chunk contains blocks -48,-64,80 to -33,319,95), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 22352 game time, 22352 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 522958960 bytes (498 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10500H CPU @ 2.50GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9bc4
	Graphics card #0 versionInfo: DriverVersion=31.0.101.2114
	Graphics card #1 name: NVIDIA GeForce GTX 1650 with Max-Q Design
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x1f9d
	Graphics card #1 versionInfo: DriverVersion=31.0.15.3141
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 31095.15
	Virtual memory used (MB): 27123.04
	Swap memory total (MB): 6697.36
	Swap memory used (MB): 427.19
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		badpackets: Bad Packets 0.4.3
		bclib: BCLib 3.0.13
			wunderlib: WunderLib 1.1.5
		betterend: Better End 4.0.10
		betternether: Better Nether 9.0.9
		borderlessmining: Borderless Mining 1.1.8+1.20.1
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.11.0
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.11.0
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.11.0
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.11.0
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.11.0
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.11.0
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.11.0
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.11.0
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.11.0
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.11.0
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.11.0
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.11.0
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.11.0
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.11.0
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.11.0
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.11.0
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.11.0
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.11.0
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.0
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.11.0
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.0
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		create: Create 0.5.1-d-build.1161+mc1.20.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.9-1
			forgeconfigapiport: Forge Config API Port 8.0.0
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.1.1127+1.20
			porting_lib_base: Porting Lib Base 2.1.1127+1.20
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.1127+1.20
				porting_lib_utility: Porting Lib Utility 2.1.1127+1.20
			porting_lib_brewing: Porting Lib Brewing 2.1.1127+1.20
			porting_lib_client_events: Porting Lib Client Events 2.1.1127+1.20
			porting_lib_entity: Porting Lib Entity 2.1.1127+1.20
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.1.1127+1.20
			porting_lib_extensions: Porting Lib Extensions 2.1.1127+1.20
				porting_lib_attributes: Porting Lib Attributes 2.1.1127+1.20
				porting_lib_common: Porting Lib Common 2.1.1127+1.20
			porting_lib_fake_players: Porting Lib Fake Players 2.1.1127+1.20
			porting_lib_models: Porting Lib Models 2.1.1127+1.20
				porting_lib_core: Porting Lib Core 2.1.1127+1.20
				porting_lib_gametest: Porting Lib GameTest 2.1.1127+1.20
				porting_lib_model_loader: Porting Lib Model Loader 2.1.1127+1.20
			porting_lib_networking: Porting Lib Networking 2.1.1127+1.20
			porting_lib_obj_loader: Porting Lib Obj Loader 2.1.1127+1.20
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.1.1127+1.20
			porting_lib_transfer: Porting Lib Transfer 2.1.1127+1.20
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		cristellib: Cristel Lib 1.1.3
			blue_endless_jankson: jankson 1.2.1
		dynamic_fps: Dynamic FPS 3.2.1
		emi: EMI 1.0.24+1.20.1+fabric
		enhancedblockentities: Enhanced Block Entities 0.9+1.20
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			spruceui: SpruceUI 5.0.0+1.20
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20.1
		fabric-api: Fabric API 0.90.7+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.12+215bbe9677
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10+57aed33f77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.2+d7b148e077
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.39+ae9f657a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.11+d7b148e077
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.0+96dfa95977
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.44+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.8+d7b148e077
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.2+4ee0bc6077
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+39a511ba77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+39a511ba77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.6+d7b148e077
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.2+1bc31aeb77
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.13+kotlin.1.9.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.22.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.0
		fabricloader: Fabric Loader 0.14.24
		farmersdelight: Farmer's Delight 1.20.1-1.4.2
		ferritecore: FerriteCore 6.0.1
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		lithium: Lithium 0.11.2
		minecraft: Minecraft 1.20.1
		modernfix: ModernFix 5.9.2+mc1.20.1
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.9
		modmenu: Mod Menu 7.2.2
		morechathistory: MoreChatHistory 1.1.1
		no-telemetry: No Telemetry 1.7.0
		nochatreports: No Chat Reports 1.20.1-v2.2.2
		patchouli: Patchouli 1.20.1-81-FABRIC
			fiber: fiber 0.23.0-2
		railways: Create: Steam 'n' Rails 1.5.1+fabric-mc1.20.1
			mm: Manningham Mills 2.3
		raised: Raised 3.1.0
		rrls: Remove Reloading Screen 3.2.0-1.20.1-fabric
		sliceanddice: Create Slice & Dice 3.0.0
		sodium: Sodium 0.4.10+build.27
		starlight: Starlight 1.1.2+fabric.dbc156f
		t_and_t: Towns and Towers 1.11.1
		terralith: Terralith 2.4.8
		voicechat: Simple Voice Chat 1.20.1-2.4.28
		wthit: wthit 8.4.1
		wwoo: William Wythers' Overhauled Overworld 2.0.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.2.1+1.20
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		zoomify: Zoomify 2.11.2
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.4.1
			dev_isxander_settxi_settxi-core: settxi-core 2.10.6
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.6
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: fabric-loader-0.14.24-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1650 with Max-Q Design/PCIe/SSE2 GL version 3.2.0 NVIDIA 531.41, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, fabric
	Current Language: en_us
	CPU: 12x Intel(R) Core(TM) i5-10500H CPU @ 2.50GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['electricbone1012'/68, l='ServerLevel[ueaeaue]', x=4249.47, y=68.14, z=-2169.58]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental

**Comment by drwoops** [comment]
please attach the file. pasting it in looses the formatting making it very difficult to read

**Comment by drwoops** [comment]
also remove starlight. it is no longer needed and causes issues

**Comment by cheesebone** [comment]
my bad, i am very new to github
[crash-2022-02-06_18.31.26-client.txt](https://github.com/Fabricators-of-Create/Create/files/13328739/crash-2022-02-06_18.31.26-client.txt)

**Comment by cheesebone** [comment]
ISSUE FIXED IT WAS STARLIGHT THANK U

**Comment by drwoops** [comment]
excellent! please consider closing this issue :)

**Comment by cheesebone** [comment]
I love u.
