### ISSUE TITLE
sodium not compatible

### ISSUE THREAD

**Issue by Dokusei1321** [Fabricators-of-Create/Create#1194]
### Describe the Bug

doesn't work with sodium v0.5.3 and cant work around it wont let me even down grade my sodium to v0.5.1 just wont work over all for me really was excited for it.

### Reproduction Steps

1. sodium v0.5.3 added to list 
2. the add the lastest version of the create fabric mod 
3. the incompatible mods
...

### Expected Result

i was hoping for it too be compatible with the mods 

### Screenshots and Videos

<img width="392" alt="Screenshot 2023-11-14 081240" src="https://github.com/Fabricators-of-Create/Create/assets/150736693/3db04493-e261-48a4-a1c2-01e79f76947c">

### Operating System

windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by drwoops** [comment]
you are very late to the party.  The issue is being worked on.  For now: create 0.5.1d sodium 0.4.10 fabric api 0.88.1 iris 1.6.4 and indium 1.0.21 are the precise versions you want

**Comment by drwoops** [comment]
please consider closing this issue. it has been reported many times before. more reports do not speed the resolution.

**Comment by Dokusei1321** [comment]
@drwoops thank you for your help and appericate all of you

**Comment by ChibiRuby** [comment]
does not work anymore. i have the exact precise versions and i have triple checked this.


---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2023-12-11 20:52:33
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'create'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at fudge.notenoughcrashes.fabric.mixinhandlers.ModLoaders.fabricEntrypoints(ModLoaders.java:9)
	at net.minecraft.class_310.redirect$dnd000$notenoughcrashes$catchFabricInit(class_310.java:21511)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: io/github/fabricators_of_create/porting_lib/entity/ExtraSpawnDataEntity
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at com.simibubi.create.AllBlocks.<clinit>(AllBlocks.java:1282)
	at com.simibubi.create.Create.onInitialize(Create.java:104)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 8 more
Caused by: java.lang.ClassNotFoundException: io.github.fabricators_of_create.porting_lib.entity.ExtraSpawnDataEntity
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 19 more

**Comment by drwoops** [comment]
@ChibiRuby open you own issue and ATTACH your crash report , don't paste it in.
