### ISSUE TITLE
when attempting to kill a mob with a deployer the game crashes

### ISSUE THREAD

**Issue by flashMonster2006** [Fabricators-of-Create/Create#1312]
### Describe the Bug

to create an automatic mob farm for withers and blaze because of the better nether mod i used a deployer however after killing a single blaze the server crashed so i also tested it on a survival and also crashed and the error that comes up is capturedDrops is 'null'.
i am on the 1.20.1 0.5.1d version using it on Modrinith
this crash can be done on a server to single player superflat

### Reproduction Steps

1.place a deployer
2.add a weapon(not needed as it still crashes without weapon but is quicker to kill)
3.spawn a mob and kill it with the deployer

### Expected Result

The mob dies and drops loot

### Screenshots and Videos

[18:11:15] [Render thread/WARN]: Received unknown attacker
[18:11:16] [Render thread/WARN]: Received unknown attacker
[18:11:16] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking block entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:105) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.forEach(java.util.function.Consumer)" because "capturedDrops" is null
	at com.simibubi.create.content.kinetics.deployer.DeployerHandler.activateInner(DeployerHandler.java:207) ~[create-fabric-0.5.1-d-build.1161+mc1.20.1.jar:?]
	at com.simibubi.create.content.kinetics.deployer.DeployerHandler.activate(DeployerHandler.java:134) ~[create-fabric-0.5.1-d-build.1161+mc1.20.1.jar:?]
	at com.simibubi.create.content.kinetics.deployer.DeployerBlockEntity.activate(DeployerBlockEntity.java:358) ~[create-fabric-0.5.1-d-build.1161+mc1.20.1.jar:?]
	at com.simibubi.create.content.kinetics.deployer.DeployerBlockEntity.tick(DeployerBlockEntity.java:244) ~[create-fabric-0.5.1-d-build.1161+mc1.20.1.jar:?]
	at com.simibubi.create.foundation.blockEntity.SmartBlockEntityTicker.tick(SmartBlockEntityTicker.java:15) ~[create-fabric-0.5.1-d-build.1161+mc1.20.1.jar:?]
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662) ~[client-intermediary.jar:?]
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_18471(class_1937.java:470) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:390) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[client-intermediary.jar:?]
	... 5 more

### Crash Report or Log

https://pastebin.com/7N0Cc3X6#google_vignette

### Operating System

windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

        - accelerateddecay 3.0.1+mc1.20.1
	- allthetrims 3.3.7
	- altorigingui 1.0.1
	- appleskin 2.5.1+mc1.20
	- architectury 9.1.12
	- balm-fabric 7.2.1
	- bclib 3.0.14
	- betterend 4.0.11
	- betternether 9.0.10
	- bettertrims 2.0.5
	- cardinal-components 5.2.2
	- carryon 2.1.2.7
	- chunky 1.3.92
	- cloth-config 11.1.118
	- clumps 12.0.0.3
	- collective 7.30
	- create 0.5.1-d-build.1161+mc1.20.1
	- create_structures 1.1.0
	- createaddition 0.9.0
	- createdeco 2.0.0-fabric-1.20.1
	- createorigins 1.2.1+1.20.1
	- dawn 5.0.0
	- decorative_blocks 4.0.3
	- deeperdarker 1.2.5
	- disable_enderman_picking_up_blocks 1.2
	- emotecraft 2.2.7-b.build.50
	- emotetweaks 4.0.2.27
	- extended_drawers 2.1.1+mc.1.20.1
	- extendedgears 2.1.0-1.20.1-0.5.1.c-fabric
	- fabric-api 0.91.0+1.20.1
	- fabric-language-kotlin 1.10.17+kotlin.1.9.22
	- fabricloader 0.15.3
	- farmersdelight 1.20.1-1.4.3
	- forgeconfigapiport 8.0.0
	- fpsreducer 1.20-2.5
	- freecam 1.2.1+1.20
	- friendsandfoes 2.0.7
	- fusion 1.1.0+c
	- geckolib 4.4
	- immediatelyfast 1.2.8+1.20.4
	- jade 11.7.0
	- jadeaddons 5.2.3
	- java 17
	- jei 15.2.0.27
	- justmobheads 7.5
	- justplayerheads 3.3
	- lazydfu 0.1.3
	- lighty 2.1.2+1.20.1
	- lithium 0.11.2
	- mavapi 1.1.3
	- mavm 1.2.4
	- midnightcontrols 1.8.2+1.20
	- midnightcontrols-extra 1.0.0
	- midnightlib 1.4.1
	- minecraft 1.20.1
	- modmenu 7.2.2
	- more-axolotl 2.0.1
	- morediscs 1.20.1-32-fabric
	- mousewheelie 1.13.0+mc1.20.1
	- naturalist 4.0.3
	- naturescompass 1.20.1-2.2.3-fabric
	- nochatreports 1.20.1-v2.2.2
	- nomorecreepersgrief 1.0.0
	- opaccreatesupport 1.3.0
	- openpartiesandclaims 0.20.4
	- origins 1.10.0
	- origins-plus-plus 2.2
	- pehkui 3.7.12+1.14.4-1.20.4
	- pickablevillagers 1.4.5+1.20.1
	- promenade 4.1.1
	- railways 1.5.1+fabric-mc1.20.1
	- rechiseled 1.1.5+b
	- rechiseledcreate 1.0.1
	- replaymod 1.20.1-2.6.14
	- shulkerboxtooltip 4.0.4+1.20.1
	- sliceanddice 3.0.0
	- starlight 1.1.2+fabric.dbc156f
	- supermartijn642configlib 1.1.8+a
	- supermartijn642corelib 1.1.16
	- terrablender 3.0.1.2
	- trade_cycling 1.20.1-1.0.10
	- villagesandpillages 1.0.0
	- voicechat 1.20.1-2.4.32
	- way2wayfabric 0.0.6
	- waystones 14.1.3
	- xaerominimap 23.9.3
	- xaeroworldmap 1.37.2
	- yet_another_config_lib_v3 3.2.1+1.20
	- yigd 2.0.0-beta.6
	- yungsapi 1.20-Fabric-4.0.2
	- zoomify 2.11.2

**Comment by skippyall** [comment]
https://github.com/Fabricators-of-Create/Create/issues/1096#issue-1879265477

**Comment by IThundxr** [comment]
Known issue, Can be closed
