### ISSUE TITLE
[Error] Cannot launch the game Fabric 0..92 + Create 0.5.1f

### ISSUE THREAD

**Issue by ElRokur** [Fabricators-of-Create/Create#1381]
### Describe the Bug

Just with those 2 mods installed, the game wont lauch

Create Fabric 0.5.1-f-build.1335+mc1.20.1
Fabric Api 0.92.0+1.20.1

It says there is a incompatible mod found, 0.15.6 is installed and 0.15.7 needed, eventhough the latest fabric api is installed

I installed them both from modrinth, if it makes any difference

### Reproduction Steps

1. Install Fabric Api 0.92
2. Install Create Fabric 0.5.1f

Game will say incompatible mods found

### Expected Result

Start the game as normal

### Screenshots and Videos

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
Hemos encontrado una solución prometedora:
	 - Cambia el mod 'Fabric Loader' (fabricloader) 0.15.6 por la versión 0.15.7 o posterior.
Dependencias no satisfechas:
	 - ¡El mod 'Create' (create) 0.5.1-f-build.1335+mc1.20.1 necesita la versión 0.15.7 o posterior de el mod 'Fabric Loader' (fabricloader), pero sólo tienes una versión incorrecta: 0.15.6!
	 - ¡El mod 'Porting Lib Accessors' (porting_lib_accessors) 2.3.0+1.20.1 necesita la versión 0.15.7 o posterior de el mod 'Fabric Loader' (fabricloader), pero sólo tienes una versión incorrecta: 0.15.6!
	 - ¡El mod 'Porting Lib Base' (porting_lib_base) 2.3.0+1.20.1 necesita la versión 0.15.7 o posterior de el mod 'Fabric Loader' (fabricloader), pero sólo tienes una versión incorrecta: 0.15.6!
	 - ¡El mod 'Porting Lib Entity' (porting_lib_entity) 2.3.0+1.20.1 necesita la versión 0.15.7 o posterior de el mod 'Fabric Loader' (fabricloader), pero sólo tienes una versión incorrecta: 0.15.6!
	 - ¡El mod 'Porting Lib Extensions' (porting_lib_extensions) 2.3.0+1.20.1 necesita la versión 0.15.7 o posterior de el mod 'Fabric Loader' (fabricloader), pero sólo tienes una versión incorrecta: 0.15.6!
	 - ¡El mod 'Porting Lib Networking' (porting_lib_networking) 2.3.0+1.20.1 necesita la versión 0.15.7 o posterior de el mod 'Fabric Loader' (fabricloader), pero sólo tienes una versión incorrecta: 0.15.6!
	 - ¡El mod 'Porting Lib Obj Loader' (porting_lib_obj_loader) 2.3.0+1.20.1 necesita la versión 0.15.7 o posterior de el mod 'Fabric Loader' (fabricloader), pero sólo tienes una versión incorrecta: 0.15.6!
	 - ¡El mod 'Porting Lib Tags' (porting_lib_tags) 3.0 necesita la versión 0.15.7 o posterior de el mod 'Fabric Loader' (fabricloader), pero sólo tienes una versión incorrecta: 0.15.6!
	 - ¡El mod 'Porting Lib Transfer' (porting_lib_transfer) 2.3.0+1.20.1 necesita la versión 0.15.7 o posterior de el mod 'Fabric Loader' (fabricloader), pero sólo tienes una versión incorrecta: 0.15.6!
	 - ¡El mod 'Porting Lib Models' (porting_lib_models) 2.3.0+1.20.1 necesita la versión 0.15.7 o posterior de el mod 'Fabric Loader' (fabricloader), pero sólo tienes una versión incorrecta: 0.15.6!
	 - ¡El mod 'Porting Lib Client Events' (porting_lib_client_events) 2.3.0+1.20.1 necesita la versión 0.15.7 o posterior de el mod 'Fabric Loader' (fabricloader), pero sólo tienes una versión incorrecta: 0.15.6!
	 - ¡El mod 'Porting Lib Attributes' (porting_lib_attributes) 2.3.0+1.20.1 necesita la versión 0.15.7 o posterior de el mod 'Fabric Loader' (fabricloader), pero sólo tienes una versión incorrecta: 0.15.6!
	 - ¡El mod 'Porting Lib Brewing' (porting_lib_brewing) 2.3.0+1.20.1 necesita la versión 0.15.7 o posterior de el mod 'Fabric Loader' (fabricloader), pero sólo tienes una versión incorrecta: 0.15.6!
	 - ¡El mod 'Porting Lib Common' (porting_lib_common) 2.3.0+1.20.1 necesita la versión 0.15.7 o posterior de el mod 'Fabric Loader' (fabricloader), pero sólo tienes una versión incorrecta: 0.15.6!
	 - ¡El mod 'Porting Lib Core' (porting_lib_core) 2.3.0+1.20.1 necesita la versión 0.15.7 o posterior de el mod 'Fabric Loader' (fabricloader), pero sólo tienes una versión incorrecta: 0.15.6!
	 - ¡El mod 'Porting Lib Tool Actions' (porting_lib_tool_actions) 2.3.0+1.20.1 necesita la versión 0.15.7 o posterior de el mod 'Fabric Loader' (fabricloader), pero sólo tienes una versión incorrecta: 0.15.6!
	 - ¡El mod 'Porting Lib Fluids' (porting_lib_fluids) 2.3.0+1.20.1 necesita la versión 0.15.7 o posterior de el mod 'Fabric Loader' (fabricloader), pero sólo tienes una versión incorrecta: 0.15.6!
	 - ¡El mod 'Porting Lib Lazy Register' (porting_lib_lazy_registration) 2.3.0+1.20.1 necesita la versión 0.15.7 o posterior de el mod 'Fabric Loader' (fabricloader), pero sólo tienes una versión incorrecta: 0.15.6!
	 - ¡El mod 'Porting Lib Mixin Extensions' (porting_lib_mixin_extensions) 2.3.0+1.20.1 necesita la versión 0.15.7 o posterior de el mod 'Fabric Loader' (fabricloader), pero sólo tienes una versión incorrecta: 0.15.6!
	 - ¡El mod 'Porting Lib Model Loader' (porting_lib_model_loader) 2.3.0+1.20.1 necesita la versión 0.15.7 o posterior de el mod 'Fabric Loader' (fabricloader), pero sólo tienes una versión incorrecta: 0.15.6!
	 - ¡El mod 'Porting Lib Utility' (porting_lib_utility) 2.3.0+1.20.1 necesita la versión 0.15.7 o posterior de el mod 'Fabric Loader' (fabricloader), pero sólo tienes una versión incorrecta: 0.15.6!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

![image](https://github.com/Fabricators-of-Create/Create/assets/140526008/32067ccb-8e78-4a1e-bf96-0871cfb0d294)

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

Fabric Api 0.92

**Comment by ElRokur** [comment]
NVM, please close, the problem is using outdated loader version as default, here how to change it to the latest if someone is interested

https://imgur.com/a/6ALtBRd
