### ISSUE TITLE
Incompatible with Cardboard MOD

### ISSUE THREAD

**Issue by pedroreglero** [Fabricators-of-Create/Create#1467]
### Describe the Bug

The server crashes when loading, if I remove Cardboard it works, it's an incompatibility.

`Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[17:24:19] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.15.10
[17:24:20] [ForkJoinPool-1-worker-3/WARN]: Mod com_github_isaiahpatton_specialsource uses the version master-SNAPSHOT which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'master'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[17:24:20] [ForkJoinPool-1-worker-4/WARN]: Mod icommon-bundle uses the version bundle which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'bundle'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[17:24:20] [main/INFO]: Loading 109 mods:
        - ad_astra 1.15.18
           \-- javazoom_jlayer 1.0.1
        - appleskin 2.5.1+mc1.20
           \-- cloth-config 11.0.99
                \-- cloth-basic-math 0.6.1
        - architectury 9.2.14
        - betteradvancements 0.3.2.162
        - betterfurnacesreforged 1.1.3
        - bookshelf 20.1.10
        - botarium 2.3.3
           \-- team_reborn_energy 3.0.0
        - cardboard 5
           \-- com_github_isaiahpatton_specialsource master-SNAPSHOT
        - create 0.5.1-f-build.1335+mc1.20.1
           |-- com_electronwill_night-config_core 3.6.5
           |-- com_electronwill_night-config_toml 3.6.5
           |-- com_google_code_findbugs_jsr305 3.0.2
           |-- flywheel 0.6.10-2
           |-- forgeconfigapiport 8.0.0
           |-- milk 1.2.60
           |    \-- dripstone_fluid_lib 3.0.2
           |-- porting_lib_accessors 2.3.0+1.20.1
           |    \-- porting_lib_core 2.3.0+1.20.1
           |-- porting_lib_base 2.3.0+1.20.1
           |    |-- porting_lib_attributes 2.3.0+1.20.1
           |    |-- porting_lib_common 2.3.0+1.20.1
           |    |-- porting_lib_core 2.3.0+1.20.1
           |    |-- porting_lib_fluids 2.3.0+1.20.1
           |    |-- porting_lib_lazy_registration 2.3.0+1.20.1
           |    |-- porting_lib_mixin_extensions 2.3.0+1.20.1
           |    |-- porting_lib_utility 2.3.0+1.20.1
           |    \-- reach-entity-attributes 2.4.0
           |-- porting_lib_brewing 2.3.0+1.20.1
           |    \-- porting_lib_core 2.3.0+1.20.1
           |-- porting_lib_client_events 2.3.0+1.20.1
           |    \-- porting_lib_core 2.3.0+1.20.1
           |-- porting_lib_entity 2.3.0+1.20.1
           |    |-- porting_lib_core 2.3.0+1.20.1
           |    \-- porting_lib_mixin_extensions 2.3.0+1.20.1
           |-- porting_lib_extensions 2.3.0+1.20.1
           |    |-- porting_lib_attributes 2.3.0+1.20.1
           |    |-- porting_lib_common 2.3.0+1.20.1
           |    |-- porting_lib_core 2.3.0+1.20.1
           |    \-- reach-entity-attributes 2.4.0
           |-- porting_lib_models 2.3.0+1.20.1
           |    |-- porting_lib_core 2.3.0+1.20.1
           |    |-- porting_lib_fluids 2.3.0+1.20.1
           |    \-- porting_lib_model_loader 2.3.0+1.20.1
           |-- porting_lib_networking 2.3.0+1.20.1
           |    \-- porting_lib_core 2.3.0+1.20.1
           |-- porting_lib_obj_loader 2.3.0+1.20.1
           |    |-- porting_lib_core 2.3.0+1.20.1
           |    \-- porting_lib_model_loader 2.3.0+1.20.1
           |-- porting_lib_tags 3.0
           |    \-- porting_lib_core 2.3.0+1.20.1
           |-- porting_lib_tool_actions 2.3.0+1.20.1
           |    \-- porting_lib_core 2.3.0+1.20.1
           |-- porting_lib_transfer 2.3.0+1.20.1
           |    |-- porting_lib_core 2.3.0+1.20.1
           |    \-- porting_lib_fluids 2.3.0+1.20.1
           |-- reach-entity-attributes 2.4.0
           \-- registrate-fabric 1.3.62-MC1.20.1
                |-- porting_lib_data 2.1.1090+1.20
                |    \-- porting_lib_gametest 2.1.1090+1.20
                \-- porting_lib_model_generators 2.1.1090+1.20
                     |-- porting_lib_gametest 2.1.1090+1.20
                     \-- porting_lib_model_materials 2.1.1090+1.20
        - createaddition 1.2.3
        - dummmmmmy 1.20-1.8.14
        - fabric-api 0.92.1+1.20.1
           |-- fabric-api-base 0.4.31+1802ada577
           |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
           |-- fabric-biome-api-v1 13.0.13+1802ada577
           |-- fabric-block-api-v1 1.0.11+1802ada577
           |-- fabric-block-view-api-v2 1.0.1+1802ada577
           |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
           |-- fabric-client-tags-api-v1 1.1.2+1802ada577
           |-- fabric-command-api-v1 1.2.34+f71b366f77
           |-- fabric-command-api-v2 2.2.13+1802ada577
           |-- fabric-commands-v0 0.2.51+df3654b377
           |-- fabric-containers-v0 0.1.64+df3654b377
           |-- fabric-content-registries-v0 4.0.11+1802ada577
           |-- fabric-convention-tags-v1 1.5.5+1802ada577
           |-- fabric-crash-report-info-v1 0.2.19+1802ada577
           |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
           |-- fabric-data-generation-api-v1 12.3.4+1802ada577
           |-- fabric-dimensions-v1 2.1.54+1802ada577
           |-- fabric-entity-events-v1 1.6.0+1c78457f77
           |-- fabric-events-interaction-v0 0.6.2+1802ada577
           |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
           |-- fabric-game-rule-api-v1 1.0.40+1802ada577
           |-- fabric-item-api-v1 2.1.28+1802ada577
           |-- fabric-item-group-api-v1 4.0.12+1802ada577
           |-- fabric-key-binding-api-v1 1.0.37+1802ada577
           |-- fabric-keybindings-v0 0.2.35+df3654b377
           |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
           |-- fabric-loot-api-v2 1.2.1+1802ada577
           |-- fabric-loot-tables-v1 1.1.45+9e7660c677
           |-- fabric-message-api-v1 5.1.9+1802ada577
           |-- fabric-mining-level-api-v1 2.1.50+1802ada577
           |-- fabric-model-loading-api-v1 1.0.3+1802ada577
           |-- fabric-models-v0 0.4.2+9386d8a777
           |-- fabric-networking-api-v1 1.3.11+1802ada577
           |-- fabric-networking-v0 0.3.51+df3654b377
           |-- fabric-object-builder-api-v1 11.1.3+1802ada577
           |-- fabric-particles-v1 1.1.2+1802ada577
           |-- fabric-recipe-api-v1 1.0.21+1802ada577
           |-- fabric-registry-sync-v0 2.3.3+1802ada577
           |-- fabric-renderer-api-v1 3.2.1+1802ada577
           |-- fabric-renderer-indigo 1.5.1+1802ada577
           |-- fabric-renderer-registries-v1 3.2.46+df3654b377
           |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
           |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
           |-- fabric-rendering-v0 1.1.49+df3654b377
           |-- fabric-rendering-v1 3.0.8+1802ada577
           |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
           |-- fabric-resource-loader-v0 0.11.10+1802ada577
           |-- fabric-screen-api-v1 2.0.8+1802ada577
           |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
           |-- fabric-sound-api-v1 1.0.13+1802ada577
           |-- fabric-transfer-api-v1 3.3.5+8dd72ea377
           \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
        - fabricloader 0.15.10
           \-- mixinextras 0.3.5
        - factory_api 2.1.4
        - icommon-bundle bundle
           \-- icommon 1.20
        - jade 11.8.0
        - jadeaddons 5.2.5
        - java 17
        - jei 15.3.0.4
        - jeresources 1.4.0.247
        - minecraft 1.20.1
        - moonlight 1.20-2.11.12
        - notenoughanimations 1.7.2
        - player-animator 1.0.2-rc1+1.20
        - resourcefulconfig 2.1.2
        - resourcefullib 2.1.24
           |-- com_teamresourceful_bytecodecs 1.0.2
           \-- com_teamresourceful_yabn 1.0.3
        - supplementaries 1.20-2.8.10
           \-- mixinsquared 0.1.1
        - xaerominimap 24.1.1
[17:24:20] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/pedro/mcServerPros/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[17:24:20] [main/INFO]: Compatibility level set to JAVA_17
[17:24:20] [main/WARN]: Reference map 'BetterFurnaces-fabric-refmap.json' for betterfurnaces.mixins.json could not be read. If this is a development environment you can ignore this message
[17:24:20] [main/INFO]: Please wait, Scanning plugins for events...
[17:24:20] [main/INFO]: Found: 0 (Took: 0ms)
[17:24:20] [main/INFO]: Loading Libraries...
[17:24:21] [main/INFO]: Debug: Loading library paper-api-1.19.4-550.jar
[17:24:21] [main/INFO]: Debug: Loading library sqlite-jdbc-3.41.0.0.jar
[17:24:21] [main/INFO]: Debug: Loading library mysql-connector-j-8.0.32.jar
[17:24:21] [main/INFO]: Debug: Loading library commons-lang-2.6.jar
[17:24:21] [main/INFO]: Debug: Loading library commons-collections4-4.4.jar
[17:24:21] [main/INFO]: Debug: Loading library commons-collections-3.2.1.jar
[17:24:21] [main/WARN]: Reference map 'dummmmmmy-fabric-refmap.json' for dummmmmmy.mixins.json could not be read. If this is a development environment you can ignore this message
[17:24:21] [main/WARN]: Reference map 'JustEnoughResources-Fabric-1.20.1-refmap.json' for jeresources.mixins.json could not be read. If this is a development environment you can ignore this message
[17:24:21] [main/WARN]: Error loading class: net/minecraft/class_906 (java.lang.ClassNotFoundException: net/minecraft/class_906)
[17:24:21] [main/WARN]: @Mixin target net.minecraft.class_906 was not found porting_lib_tool_actions.mixins.json:FishingHookRendererMixin from mod porting_lib_tool_actions
[17:24:22] [main/INFO]: Architectury Mod detected! Disabling async chat from NetworkHandler.
[17:24:22] [main/INFO]: =======================================================
[17:24:22] [main/INFO]:  iCommon - Isaiah's common library for mods.
[17:24:22] [main/INFO]:  Copyright (c) 2018-2023 Isaiah. Running on MC 1.20.1
[17:24:22] [main/INFO]: =======================================================
[17:24:22] [main/INFO]: Applying mixin: MixinMinecraftServer...
[17:24:22] [main/WARN]: Error loading class: net/minecraft/class_5616 (java.lang.ClassNotFoundException: net/minecraft/class_5616)
[17:24:22] [main/WARN]: @Mixin target net.minecraft.class_5616 was not found registrate-fabric.mixins.json:accessor.BlockEntityRenderersAccessor from mod registrate-fabric
[17:24:22] [main/INFO]: Applying mixin: R1_20.MixinMinecraftServer...
[17:24:22] [main/INFO]: Applying mixin: R1_20.MixinEntity...
[17:24:22] [main/INFO]: Applying mixin: R1_20.MixinPlayer...
[17:24:22] [main/INFO]: Applying mixin: R1_20.MixinBlockEntity...
[17:24:22] [main/INFO]: Applying mixin: R1_20.MixinChestBlockEntity...
[17:24:22] [main/INFO]: Applying mixin: R1_20.MixinCampfireBlockEntity...
[17:24:22] [main/INFO]: Applying mixin: R1_20.MixinScreenHandler...
[17:24:22] [main/INFO]: Applying mixin: R1_20.MixinChunkGenerator...
[17:24:22] [main/INFO]: Applying mixin: R1_20.MixinPersistentStateManager...
[17:24:22] [main/INFO]: Applying mixin: R1_20.MixinPlayerManager...
[17:24:22] [main/INFO]: Applying mixin: R1_20.MixinHeighttmap...
[17:24:22] [main/INFO]: Applying mixin: R1_20.MixinLeavesBlock...
[17:24:22] [main/INFO]: Applying mixin: R1_20.MixinCat...
[17:24:22] [main/INFO]: Applying mixin: R1_20.MixinWorld_18...
[17:24:22] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[17:24:25] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=2 on porting_lib_entity.mixins.json:common.LivingEntityMixin from mod porting_lib_entity::handler$bkn000$porting_lib_entity$port_lib$onFinishUsing exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[17:24:31] [main/ERROR]: Critical injection failure: LVT in net/minecraft/class_1757::method_7861(Lnet/minecraft/class_1799;Lnet/minecraft/class_1937;Lnet/minecraft/class_1309;)Lnet/minecraft/class_1799; has incompatible changes at opcode 149 in callback porting_lib_entity.mixins.json:common.ChorusFruitItemMixin from mod porting_lib_entity->@Inject::port_lib$finishUsingItem(Lnet/minecraft/class_1799;Lnet/minecraft/class_1937;Lnet/minecraft/class_1309;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/class_1799;DDDIDDD)V.
 Expected: [Lnet/minecraft/class_1799;, D, D, D, I, D, D, D]
    Found: [Lnet/minecraft/class_1799;, I, D, D, D, Lorg/bukkit/entity/Player;, Lorg/bukkit/event/player/PlayerTeleportEvent;]
Available: [Lnet/minecraft/class_1799;, I, D, D, D, Lorg/bukkit/entity/Player;, Lorg/bukkit/event/player/PlayerTeleportEvent;]
[17:24:31] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.10.jar:?]
Caused by: java.lang.ExceptionInInitializerError
        at net.minecraft.class_2358.method_10199(class_2358.java:326) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
        ... 3 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1757 failed
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.10.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at net.minecraft.class_6089.method_9530(class_6089.java:56) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1032) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1028) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970.method_9549(class_4970.java:349) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1293) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:843) ~[server-intermediary.jar:?]
        at net.minecraft.class_2246.<clinit>(class_2246.java:1185) ~[server-intermediary.jar:?]
        at net.minecraft.class_2358.method_10199(class_2358.java:326) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
        ... 3 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.10.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at net.minecraft.class_6089.method_9530(class_6089.java:56) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1032) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1028) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970.method_9549(class_4970.java:349) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1293) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:843) ~[server-intermediary.jar:?]
        at net.minecraft.class_2246.<clinit>(class_2246.java:1185) ~[server-intermediary.jar:?]
        at net.minecraft.class_2358.method_10199(class_2358.java:326) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
        ... 3 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_1757::method_7861(Lnet/minecraft/class_1799;Lnet/minecraft/class_1937;Lnet/minecraft/class_1309;)Lnet/minecraft/class_1799; has incompatible changes at opcode 149 in callback porting_lib_entity.mixins.json:common.ChorusFruitItemMixin from mod porting_lib_entity->@Inject::port_lib$finishUsingItem(Lnet/minecraft/class_1799;Lnet/minecraft/class_1937;Lnet/minecraft/class_1309;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/class_1799;DDDIDDD)V.
 Expected: [Lnet/minecraft/class_1799;, D, D, D, I, D, D, D]
    Found: [Lnet/minecraft/class_1799;, I, D, D, D, Lorg/bukkit/entity/Player;, Lorg/bukkit/event/player/PlayerTeleportEvent;]
Available: [Lnet/minecraft/class_1799;, I, D, D, D, Lorg/bukkit/entity/Player;, Lorg/bukkit/event/player/PlayerTeleportEvent;]
        at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:544) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:494) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:277) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1377) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.10.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at net.minecraft.class_6089.method_9530(class_6089.java:56) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1032) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1028) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970.method_9549(class_4970.java:349) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1293) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:843) ~[server-intermediary.jar:?]
        at net.minecraft.class_2246.<clinit>(class_2246.java:1185) ~[server-intermediary.jar:?]
        at net.minecraft.class_2358.method_10199(class_2358.java:326) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
        ... 3 more
`

### Reproduction Steps

1.
2.
3.
...

### Expected Result

For it to work

### Operating System

MX Linux

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by pedroreglero** [comment]
It fails here
![image](https://github.com/Fabricators-of-Create/Create/assets/32191934/19ba7c51-cfc2-479a-adfe-1fa446ce7068)

**Comment by IThundxr** [comment]
Hybrid cores/hacks to load bukkit on fabric aren't supported due to the major changes they make, this should be reported to them

**Comment by pedroreglero** [comment]
Yea they are in beta, I know it's probably a Cardboard problem, just wanted to see if there was a workaround to make both mods work

**Comment by TropheusJ** [comment]
Cardboard is not and never will be compatible, and [you shouldn’t use it](https://gist.github.com/Patbox/e44844294c358b614d347d369b0fc3bf).

**Comment by pedroreglero** [comment]
Any suggestions to have plugins and mods then?

**Comment by TropheusJ** [comment]
don't. just use mods, most plugins have alternatives

**Comment by pedroreglero** [comment]
unfortunately not an option for me, but thanks for the help
