### ISSUE TITLE
Minecart issue | Error running job content is null

### ISSUE THREAD

**Issue by samve000** [Fabricators-of-Create/Create#1546]
### Describe the Bug

When I place down a minecart the log shows an error and the minecart becomes a black square. When I remove the Create mod the minecart is normal again, when I remove the better fletching table mod it becomes a minecart with a command block in it and the error won't show up.

### Reproduction Steps

1. Install create mod
2. Install Better Fletching Table mod
3. Open a world
4. Place a minecart

### Expected Result

I expect the minecart not to be a black square and the error not to pop up everytime I place a minecart.

### Screenshots and Videos

![image](https://github.com/user-attachments/assets/7ac9f1ef-32a5-45f9-9200-d641a2dcb7fe)
![2024-07-19_02 53 20](https://github.com/user-attachments/assets/bead93ce-5b6d-4219-ada3-e5840358adc0)

### Crash Report or Log

https://mclo.gs/OmY3Rc2

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

```

  [✔] bft-2.0.0
  [✔] create-fabric-0.5.1-f-build.1417+mc1.20.1
  [✔] fabric-api-0.92.2+1.20.1


```

### Additional Context

```
[Flywheel 1/ERROR] (Flywheel) Error running job
java.lang.NullPointerException: Cannot invoke "com.jozufozu.flywheel.core.materials.model.ModelData.delete()" because "this.contents" is null
	at com.jozufozu.flywheel.vanilla.MinecartInstance.tick(MinecartInstance.java:49) ~[flywheel-0.6.10-2-32bc5505f22ffdd1.jar:?]
	at com.jozufozu.flywheel.backend.instancing.InstanceManager.tickInstance(InstanceManager.java:143) ~[flywheel-0.6.10-2-32bc5505f22ffdd1.jar:?]
	at com.jozufozu.flywheel.backend.instancing.InstanceManager.lambda$tick$0(InstanceManager.java:123) ~[flywheel-0.6.10-2-32bc5505f22ffdd1.jar:?]
	at com.jozufozu.flywheel.backend.instancing.ParallelTaskEngine.processTask(ParallelTaskEngine.java:156) ~[flywheel-0.6.10-2-32bc5505f22ffdd1.jar:?]
	at com.jozufozu.flywheel.backend.instancing.ParallelTaskEngine$WorkerRunnable.run(ParallelTaskEngine.java:190) ~[flywheel-0.6.10-2-32bc5505f22ffdd1.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Comment by TropheusJ** [comment]
looks like BFT's datapack hacks are breaking flywheel somehow. Needs to be tested with flywheel 1.0 once that's ready
