### ISSUE TITLE
Incompatible mods(Create & Sound Physics Remastered )

### ISSUE THREAD

**Issue by Nayrd7** [Fabricators-of-Create/Create#1565]
### Describe the Bug

Fabric Loader log:

```
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Create' (create) 0.5.1-f-build.1417+mc1.20.1 with version 0.5.1-f-build.1417+mc1.20.1 that is compatible with:
		 - sound_physics_remastered 1.20.1-1.4.5
More details:
	 - Mod 'Create' (create) 0.5.1-f-build.1417+mc1.20.1 is incompatible with any version of mod 'Sound Physics Remastered' (sound_physics_remastered), but a matching version is present: 1.20.1-1.4.5!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

### Reproduction Steps

Start the game with mod 

### Expected Result

I wanted to see a game that started and works)

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by IThundxr** [comment]
Duplicate issue, search for your issue before opening a new one
