### ISSUE TITLE
Mechanical sticky pistons and cart assemblers disappear when activated and reappear when stopped

### ISSUE THREAD

**Issue by epicbuilder2007** [Fabricators-of-Create/Create#158]
### Describe the Bug

When the mechanical piston starts extending/retracting, the extending head and the blocks it's pushing disappears, and reappears when the mechanical piston stops.

Blocks above the cart assembler also disappear when it's on the minecart.

### Reproduction Steps

1. Build the newest source file
2. run it in a server
3. build whatever with a mechanical piston and/or a cart assembler
4. activate the build.
...

### Expected Result

blocks become invisible 

### Operating System

Windows 10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

Lithium, FerriteCore, WorldEdit, Carpet

**Comment by TropheusJ** [comment]
this is an issue with packets I introduced in [here](https://github.com/Fabricators-of-Create/Create/commit/546989afbcfe6abae5f2dac91b367ae15274fc1b), should be fixed soon. Use an earlier build for now.

**Comment by PepperCode1** [comment]
This should be fixed with the latest build. Please test it and let us know.

**Comment by epicbuilder2007** [comment]
Unfortunately no. In fact, the new build introduces a bunch of lag into it as well. The last build just disappear, then reappear, while this one lags, then disappears, then reappears once it's done.

**Comment by epicbuilder2007** [comment]
should I include a video?

**Comment by PepperCode1** [comment]
I cannot reproduce this with the latest build. Please do send a video in addition to a log.

**Comment by epicbuilder2007** [comment]
File is too big for Github so instead I uploaded it to youtube as unlisted:
https://youtu.be/dDOZgTGqKc8

Logs from server:
[11:05:59 INFO]: epicbuilder2007[My IP address] logged in with entity id 37 at (3283.31267267002, 123.24591343966004, 11922.968714870696)
[11:05:59 INFO]: epicbuilder2007 joined the game
[11:06:01 WARN]: Player epicbuilder2007 joined with another carpet version: 1.4.56+v211130
[11:06:58 INFO]: epicbuilder2007 lost connection: Disconnected
[11:06:58 INFO]: epicbuilder2007 left the game
[11:06:58 WARN]: handleDisconnection() called twice
[11:07:03 INFO]: epicbuilder2007[Lmao] logged in with entity id 1574 at (3283.31267267002, 123.24591343966004, 11922.968714870696)
[11:07:03 INFO]: epicbuilder2007 joined the game
[11:07:04 WARN]: Player epicbuilder2007 joined with another carpet version: 1.4.56+v211130
[11:08:03 INFO]: epicbuilder2007 lost connection: §cTime for authentication has expired.
[11:08:03 INFO]: epicbuilder2007 left the game
[11:08:08 INFO]: epicbuilder2007[Minecraft shouldn't print IPs out onto the console like that] logged in with entity id 3108 at (3283.31267267002, 123.24591343966004, 11922.968714870696)
[11:08:08 INFO]: epicbuilder2007 joined the game
[11:08:09 WARN]: Player epicbuilder2007 joined with another carpet version: 1.4.56+v211130
[11:09:21 INFO]: [epicbuilder2007: Teleported epicbuilder2007 to 0.500000, 90.000000, 0.500000]
[11:09:21 WARN]: epicbuilder2007 moved too quickly! -3289.6047222648963,-33.24591343966004,-11910.06144678781
[11:14:25 INFO]: [epicbuilder2007: Set own game mode to Spectator Mode]
[11:14:39 INFO]: [epicbuilder2007: Set own game mode to Creative Mode]
[11:15:14 INFO]: [epicbuilder2007: Set own game mode to Spectator Mode]
[11:15:17 INFO]: [epicbuilder2007: Set own game mode to Creative Mode]
[11:25:57 INFO]: epicbuilder2007 lost connection: Disconnected
[11:25:57 INFO]: epicbuilder2007 left the game

Suprisingly no errors there.

Log from client:
[11:11:05] [Render thread/FATAL]: Error executing task on Client
net.minecraft.class_148: Loading NBT data
	at net.minecraft.class_2507.method_10626(class_2507.java:136) ~[client-intermediary.jar:?]
	at net.minecraft.class_2507.method_10625(class_2507.java:75) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_30616(class_2540.java:450) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_10798(class_2540.java:432) ~[client-intermediary.jar:?]
	at com.simibubi.create.content.contraptions.components.structureMovement.AbstractContraptionEntity.readSpawnData(AbstractContraptionEntity.java:426) ~[create-mc1.18.1_v0.4d.jar:?]
	at net.minecraft.class_634.handler$zpc000$create$afterAddEntity(class_634.java:4413) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11112(class_634.java:404) ~[client-intermediary.jar:?]
	at net.minecraft.class_2604.method_11178(class_2604.java:93) ~[client-intermediary.jar:?]
	at net.minecraft.class_2604.method_11054(class_2604.java:14) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1080) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.io.EOFException
	at io.netty.buffer.ByteBufInputStream.readByte(ByteBufInputStream.java:212) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at net.minecraft.class_2481$1.method_23235(class_2481.java:29) ~[client-intermediary.jar:?]
	at net.minecraft.class_2481$1.method_23262(class_2481.java:25) ~[client-intermediary.jar:?]
	at net.minecraft.class_2507.method_10626(class_2507.java:131) ~[client-intermediary.jar:?]
	... 31 more
[11:11:07] [Render thread/WARN]: Received passengers for unknown entity

And then it spams the same errors for 3 minutes straight,
So error is client side.

Client computer config (i doubt this helps but it might):
Intel Core i7-10710U
16GB DDR4 Unknown Frequency
512GB Samsung SSD
Intel UHD Integrated Graphics

Server computer config:
Intel Xeon E5-2620 v3
8GB DDR4 1866MHz
X99 Motherboard
RTX 3060

**Comment by PepperCode1** [comment]
You are not using the latest build. The injector `create$afterAddEntity` does not exist anymore.

**Comment by epicbuilder2007** [comment]
didn't i clone it already... weird... ok ill try it again

**Comment by epicbuilder2007** [comment]
It works now. Sorry for wasting your time lol, might be me mixing up different source files.
