### ISSUE TITLE
[ BUG ] Fan Crash

### ISSUE THREAD

**Issue by S-N00B-1** [Fabricators-of-Create/Create#2]
Create-Refabricated Version: [40d6a9286fb0462c665f1c280d9dfbf149fe8e70](https://github.com/Create-Fabric/Create-Refabricated/actions/runs/657976637)

A downward facing fan will cause the game to crash

Attached Video Demonstration:
https://user-images.githubusercontent.com/49575478/111355907-350ca100-865e-11eb-9b1e-55ba3867c7b8.mp4

Crash Report:
```---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 16/03/21 10:45 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraft.class_2248.method_9525(class_2248.java:129)
	at com.simibubi.create.content.contraptions.components.fan.EncasedFanBlockEntity.blockBelowIsHot(EncasedFanBlockEntity.java:90)
	at com.simibubi.create.content.contraptions.components.fan.EncasedFanBlockEntity.updateGenerator(EncasedFanBlockEntity.java:77)
	at com.simibubi.create.content.contraptions.components.fan.EncasedFanBlockEntity.method_16896(EncasedFanBlockEntity.java:183)
	at net.minecraft.class_1937.method_18471(class_1937.java:510)
	at net.minecraft.class_3218.method_18765(class_3218.java:429)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$4698/465000700.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_2248.method_9525(class_2248.java:129)
	at com.simibubi.create.content.contraptions.components.fan.EncasedFanBlockEntity.blockBelowIsHot(EncasedFanBlockEntity.java:90)
	at com.simibubi.create.content.contraptions.components.fan.EncasedFanBlockEntity.updateGenerator(EncasedFanBlockEntity.java:77)
	at com.simibubi.create.content.contraptions.components.fan.EncasedFanBlockEntity.method_16896(EncasedFanBlockEntity.java:183)

-- Block entity being ticked --
Details:
	Name: create:encased_fan // com.simibubi.create.content.contraptions.components.fan.EncasedFanBlockEntity
	Block: Block{create:encased_fan}[facing=down]
	Block location: World: (-24,79,188), Chunk: (at 8,4,12 in -2,11; contains blocks -32,0,176 to -17,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Block: Block{create:encased_fan}[facing=down]
	Block location: World: (-24,79,188), Chunk: (at 8,4,12 in -2,11; contains blocks -32,0,176 to -17,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at net.minecraft.class_1937.method_18471(class_1937.java:510)
	at net.minecraft.class_3218.method_18765(class_3218.java:429)

-- Affected level --
Details:
	All players: 1 total; [class_3222['SUPERN00Bthe1'/235, l='ServerLevel[New World]', x=-23.87, y=77.00, z=188.70]]
	Chunk stats: ServerChunkCache: 2209
	Level dimension: minecraft:overworld
	Level spawn location: World: (-32,72,176), Chunk: (at 0,4,0 in -2,11; contains blocks -32,0,176 to -17,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 78295 game time, 1833 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 49222 (now: false), thunder time: 32519 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$4698/465000700.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 607399176 bytes (579 MB) / 2113929216 bytes (2016 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.3.9
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.11.15
		create: Create Fabric 0.1.0
		fabric: Fabric API 0.32.0+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.0+f9b3753b7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.1
		java: Java HotSpot(TM) 64-Bit Server VM 8
		minecraft: Minecraft 1.16.5
		modmenu: Mod Menu 1.16.8
	Player Count: 1 / 8; [class_3222['SUPERN00Bthe1'/235, l='ServerLevel[New World]', x=-23.87, y=77.00, z=188.70]]
	Data Packs: vanilla, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
```

**Comment by smellypengu** [comment]
Fixed in new version
