### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by BratishkaErik** [Fabricators-of-Create/Create#21]
```java
[13:13:16] [main/INFO]: Loading for game Minecraft 1.17.1
[13:13:16] [main/INFO]: Loading 81 mods:
	- advanced_runtime_resource_pack 0.4.4
	- canvas 1.0.2202
	- cloth-basic-math 0.5.1
	- cloth-config2 5.0.38
	- com_electronwill_night-config_core 3.6.5
	- com_electronwill_night-config_toml 3.6.5
	- com_google_code_findbugs_jsr305 3.0.2
	- com_moandjiezana_toml_toml4j 0.7.2
	- create 0.4
	- cullleaves 2.3.0
	- dynamicfps 2.0.5
	- fabric 0.40.6+1.17
	- fabric-api-base 0.4.0+5847535018
	- fabric-api-lookup-api-v1 1.3.0+cbda931818
	- fabric-biome-api-v1 3.2.0+cbda931818
	- fabric-blockrenderlayer-v1 1.1.5+a02b446318
	- fabric-command-api-v1 1.1.3+5ab9934c18
	- fabric-commands-v0 0.2.2+92519afa18
	- fabric-containers-v0 0.1.12+cbda931818
	- fabric-content-registries-v0 0.3.0+cbda931818
	- fabric-crash-report-info-v1 0.1.5+be9da31018
	- fabric-dimensions-v1 2.0.11+6cefd57718
	- fabric-entity-events-v1 1.2.3+87cc6e4c18
	- fabric-events-interaction-v0 0.4.10+fc40aa9d18
	- fabric-events-lifecycle-v0 0.2.1+92519afa18
	- fabric-game-rule-api-v1 1.0.7+cbda931818
	- fabric-item-api-v1 1.2.4+cbda931818
	- fabric-item-groups-v0 0.2.10+b7ab612118
	- fabric-key-binding-api-v1 1.0.5+5847535018
	- fabric-keybindings-v0 0.2.2+36b77c3e18
	- fabric-language-kotlin 1.6.5+kotlin.1.5.31
	- fabric-lifecycle-events-v1 1.4.5+5847535018
	- fabric-loot-tables-v1 1.0.4+a02b446318
	- fabric-mining-levels-v0 0.1.3+92519afa18
	- fabric-models-v0 0.3.0+a02b446318
	- fabric-networking-api-v1 1.0.13+cbda931818
	- fabric-networking-blockentity-v0 0.2.11+a02b446318
	- fabric-networking-v0 0.3.2+92519afa18
	- fabric-object-builder-api-v1 1.10.9+cbda931818
	- fabric-object-builders-v0 0.7.3+a02b446318
	- fabric-particles-v1 0.2.4+a02b446318
	- fabric-registry-sync-v0 0.7.11+7931163218
	- fabric-renderer-api-v1 0.4.4+cbda931818
	- fabric-renderer-indigo 0.4.8+cbda931818
	- fabric-renderer-registries-v1 3.2.4+7931163218
	- fabric-rendering-data-attachment-v1 0.1.5+a02b446318
	- fabric-rendering-fluids-v1 0.1.14+4658223018
	- fabric-rendering-v0 1.1.5+7931163218
	- fabric-rendering-v1 1.9.0+7931163218
	- fabric-resource-loader-v0 0.4.9+5847535018
	- fabric-screen-api-v1 1.0.4+cbda931818
	- fabric-screen-handler-api-v1 1.1.8+cbda931818
	- fabric-structure-api-v1 1.1.13+5ab9934c18
	- fabric-tag-extensions-v0 1.2.1+b06cb95b18
	- fabric-textures-v0 1.0.6+a02b446318
	- fabric-tool-attribute-api-v1 1.2.12+b7ab612118
	- fabric-transfer-api-v1 1.4.0+7931163218
	- fabricloader 0.12.2
	- flywheel 1.17-0.3.0.2
	- frex 6.0.171
	- io_vram_bitkit 1.0.1
	- io_vram_bitraster 1.5.50
	- io_vram_special-circumstances 1.10.7
	- jankson 3.0.1+j1.2.0
	- java 16
	- json-model-extensions 1.22.218
	- lazydfu 0.1.2
	- midnightlib 0.2.5
	- minecraft 1.17.1
	- modmenu 2.0.14
	- org_anarres_jcpp 1.4.14
	- org_jetbrains_kotlin_kotlin-reflect 1.5.31
	- org_jetbrains_kotlin_kotlin-stdlib 1.5.31
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.5.31
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.5.31
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.5.2
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.5.2
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.0
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.0
	- reach-entity-attributes 2.1.1
	- registrate 0.1.10
[13:13:16] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/home/bratishkaerik/.local/share/multimc/libraries/net/fabricmc/sponge-mixin/0.10.3+mixin.0.8.4/sponge-mixin-0.10.3+mixin.0.8.4.jar Service=Knot/Fabric Env=CLIENT
[13:13:16] [main/INFO]: Compatibility level set to JAVA_16
[13:13:16] [main/WARN]: Reference map 'create.refmap.json' for create.mixins.json could not be read. If this is a development environment you can ignore this message
[13:13:16] [main/INFO]: I used the json to destroy the json
[13:13:17] [main/ERROR]: Mixin apply failed create.mixins.json:EntityContraptionInteractionMixin -> net.minecraft.class_1297: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on movementMixin could not find any targets matching 'move' in net.minecraft.class_1297. No refMap loaded. [PREINJECT Applicator Phase -> create.mixins.json:EntityContraptionInteractionMixin -> Prepare Injections ->  -> handler$baa000$movementMixin(Lnet/minecraft/class_1313;Lnet/minecraft/class_243;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on movementMixin could not find any targets matching 'move' in net.minecraft.class_1297. No refMap loaded. [PREINJECT Applicator Phase -> create.mixins.json:EntityContraptionInteractionMixin -> Prepare Injections ->  -> handler$baa000$movementMixin(Lnet/minecraft/class_1313;Lnet/minecraft/class_243;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at jdk.internal.reflect.GeneratedConstructorAccessor18.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330) ~[sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.3+mixin.0.8.4.jar:0.10.3+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222) ~[fabric-loader-0.12.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133) ~[fabric-loader-0.12.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.2.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:103) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_3523.<clinit>(class_3523.java:13) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_5471.<clinit>(class_5471.java:11) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_5458.method_30573(class_5458.java:44) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:75) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:723) [?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:74) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:266) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:44) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:139) [intermediary-minecraft-1.17.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568) [fabric-loader-0.12.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.12.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Exiting with -1
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Minecraft has crashed
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:571)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	... 8 more
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_3523.<clinit>(class_3523.java:13)
	at net.minecraft.class_5471.<clinit>(class_5471.java:11)
	at net.minecraft.class_5458.method_30573(class_5458.java:44)
	at net.minecraft.class_5458.method_30566(class_5458.java:75)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:723)
	at net.minecraft.class_5458.<clinit>(class_5458.java:74)
	at net.minecraft.class_2378.<clinit>(class_2378.java:266)
	at net.minecraft.class_2966.method_12851(class_2966.java:44)
	at net.minecraft.client.main.Main.main(Main.java:139)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	... 10 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1297 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:224)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.minecraft.class_2246.<clinit>(class_2246.java:103)
	... 24 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222)
	... 28 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [create.mixins.json:EntityContraptionInteractionMixin] from phase [DEFAULT] in config [create.mixins.json] from mod [create] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:637)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:588)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 31 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on movementMixin could not find any targets matching 'move' in net.minecraft.class_1297. No refMap loaded. [PREINJECT Applicator Phase -> create.mixins.json:EntityContraptionInteractionMixin -> Prepare Injections ->  -> handler$baa000$movementMixin(Lnet/minecraft/class_1313;Lnet/minecraft/class_243;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308)
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
	at jdk.internal.reflect.GeneratedConstructorAccessor18.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 31 more
```

**Comment by BratishkaErik** [comment]
Hmmmmm, it works in dev environment ( ./gradlew runClient )...

**Comment by BratishkaErik** [comment]
Ok, animations don't work with Canvas

**Comment by FoxieFlakey** [comment]
> Hmmmmm, it works in dev environment ( ./gradlew runClient )...

you should remap the jar before putting it on normal client `./gradlew remapJar` (i guess you do `./gradlew jar`)  if you want to run it on normal client

**Comment by Herbing1** [comment]
what should i do for remap the jar，i dont understand

**Comment by TropheusJ** [comment]
The project is not yet ready for use. If you don’t know what you’re doing, we’re not going to help until we’ve made a release. 
The mod still crashes in production even with latest changes. Please just wait.
