### ISSUE TITLE
[ BUG ] Pully Crash

### ISSUE THREAD

**Issue by S-N00B-1** [Fabricators-of-Create/Create#3]
Description:
Attempting to move a linear chassis with a pully will cause the game to crash
Version:
[733123c](https://github.com/Create-Fabric/Create-Refabricated/commit/733123c57ab7a0f887358240b80639ec9fc73a4f)
Crash Report:
```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 17/03/21 10:20 PM
Description: Ticking block entity

java.lang.ClassCastException: com.mojang.datafixers.util.Either$Left cannot be cast to net.minecraft.class_2520
	at com.simibubi.create.content.contraptions.components.structureMovement.Contraption.writeBlocksCompound(Contraption.java:750)
	at com.simibubi.create.content.contraptions.components.structureMovement.Contraption.writeNBT(Contraption.java:667)
	at com.simibubi.create.content.contraptions.components.structureMovement.pulley.PulleyContraption.writeNBT(PulleyContraption.java:46)
	at com.simibubi.create.content.contraptions.components.structureMovement.AbstractContraptionEntity.writeAdditional(AbstractContraptionEntity.java:390)
	at com.simibubi.create.content.contraptions.components.structureMovement.ControlledContraptionEntity.writeAdditional(ControlledContraptionEntity.java:75)
	at com.simibubi.create.content.contraptions.components.structureMovement.AbstractContraptionEntity.writeSpawnData(AbstractContraptionEntity.java:379)
	at net.minecraft.class_2604.setExtraData(class_2604.java:536)
	at net.minecraft.class_2604.handler$zhd000$onEntityCtor(class_2604.java:525)
	at net.minecraft.class_2604.<init>(class_2604.java:56)
	at net.minecraft.class_2604.<init>(class_2604.java:51)
	at com.simibubi.create.content.contraptions.components.structureMovement.AbstractContraptionEntity.method_18002(AbstractContraptionEntity.java:373)
	at net.minecraft.class_3231.method_18757(class_3231.java:224)
	at net.minecraft.class_3231.method_18760(class_3231.java:214)
	at net.minecraft.class_3898$class_3208.method_18736(class_3898.java:1238)
	at net.minecraft.class_3898$class_3208.method_18729(class_3898.java:1265)
	at net.minecraft.class_3898.method_18701(class_3898.java:1020)
	at net.minecraft.class_3215.method_18755(class_3215.java:477)
	at net.minecraft.class_3218.method_18778(class_3218.java:933)
	at net.minecraft.class_3218.method_14175(class_3218.java:835)
	at net.minecraft.class_3218.method_8649(class_3218.java:765)
	at com.simibubi.create.content.contraptions.components.structureMovement.pulley.PulleyBlockEntity.assemble(PulleyBlockEntity.java:94)
	at com.simibubi.create.content.contraptions.components.structureMovement.piston.LinearActuatorBlockEntity.method_16896(LinearActuatorBlockEntity.java:82)
	at net.minecraft.class_1937.method_18471(class_1937.java:510)
	at net.minecraft.class_3218.method_18765(class_3218.java:429)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$4757/622452975.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.simibubi.create.content.contraptions.components.structureMovement.Contraption.writeBlocksCompound(Contraption.java:750)
	at com.simibubi.create.content.contraptions.components.structureMovement.Contraption.writeNBT(Contraption.java:667)
	at com.simibubi.create.content.contraptions.components.structureMovement.pulley.PulleyContraption.writeNBT(PulleyContraption.java:46)
	at com.simibubi.create.content.contraptions.components.structureMovement.AbstractContraptionEntity.writeAdditional(AbstractContraptionEntity.java:390)
	at com.simibubi.create.content.contraptions.components.structureMovement.ControlledContraptionEntity.writeAdditional(ControlledContraptionEntity.java:75)
	at com.simibubi.create.content.contraptions.components.structureMovement.AbstractContraptionEntity.writeSpawnData(AbstractContraptionEntity.java:379)
	at net.minecraft.class_2604.setExtraData(class_2604.java:536)
	at net.minecraft.class_2604.handler$zhd000$onEntityCtor(class_2604.java:525)
	at net.minecraft.class_2604.<init>(class_2604.java:56)
	at net.minecraft.class_2604.<init>(class_2604.java:51)
	at com.simibubi.create.content.contraptions.components.structureMovement.AbstractContraptionEntity.method_18002(AbstractContraptionEntity.java:373)
	at net.minecraft.class_3231.method_18757(class_3231.java:224)
	at net.minecraft.class_3231.method_18760(class_3231.java:214)
	at net.minecraft.class_3898$class_3208.method_18736(class_3898.java:1238)
	at net.minecraft.class_3898$class_3208.method_18729(class_3898.java:1265)
	at net.minecraft.class_3898.method_18701(class_3898.java:1020)
	at net.minecraft.class_3215.method_18755(class_3215.java:477)
	at net.minecraft.class_3218.method_18778(class_3218.java:933)
	at net.minecraft.class_3218.method_14175(class_3218.java:835)
	at net.minecraft.class_3218.method_8649(class_3218.java:765)
	at com.simibubi.create.content.contraptions.components.structureMovement.pulley.PulleyBlockEntity.assemble(PulleyBlockEntity.java:94)
	at com.simibubi.create.content.contraptions.components.structureMovement.piston.LinearActuatorBlockEntity.method_16896(LinearActuatorBlockEntity.java:82)

-- Block entity being ticked --
Details:
	Name: create:rope_pulley // com.simibubi.create.content.contraptions.components.structureMovement.pulley.PulleyBlockEntity
	Block: Block{create:rope_pulley}[axis=x]
	Block location: World: (-283,76,147), Chunk: (at 5,4,3 in -18,9; contains blocks -288,0,144 to -273,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Block: Block{create:rope_pulley}[axis=x]
	Block location: World: (-283,76,147), Chunk: (at 5,4,3 in -18,9; contains blocks -288,0,144 to -273,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at net.minecraft.class_1937.method_18471(class_1937.java:510)
	at net.minecraft.class_3218.method_18765(class_3218.java:429)

-- Affected level --
Details:
	All players: 1 total; [class_3222['SUPERN00Bthe1'/121, l='ServerLevel[New World]', x=-286.20, y=75.03, z=146.90]]
	Chunk stats: ServerChunkCache: 2914
	Level dimension: minecraft:overworld
	Level spawn location: World: (-32,72,176), Chunk: (at 0,4,0 in -2,11; contains blocks -32,0,176 to -17,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 97501 game time, 5603 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 30016 (now: false), thunder time: 13313 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$4757/622452975.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1355554176 bytes (1292 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.3.9
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.11.15
		create: Create Fabric 0.1.0
		fabric: Fabric API 0.32.0+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.0+f9b3753b7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.1
		java: Java HotSpot(TM) 64-Bit Server VM 8
		minecraft: Minecraft 1.16.5
		modmenu: Mod Menu 1.16.8
	Player Count: 1 / 8; [class_3222['SUPERN00Bthe1'/121, l='ServerLevel[New World]', x=-286.20, y=75.03, z=146.90]]
	Data Packs: vanilla, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
```

**Comment by smellypengu** [comment]
We are aware of this issue. Currently happens with all contraptions and we are working on fixing it. I’ll close this issue once it’s been resolved.

**Comment by smellypengu** [comment]
A bit late but this issue has been fixed in latest versions.
