### ISSUE TITLE
a possible bug with create

### ISSUE THREAD

**Issue by raptop** [Fabricators-of-Create/Create#621]
minecraft crashes when starting, and checking the crash report i found a line that said something about create
playing on 1.19.2 fabric

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2022-11-23 19:49:30
Description: Rendering overlay

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5944.method_34583(String, Object)" because "$$2" is null
	at net.minecraft.class_291.method_34431(class_291.java:128)
	at net.minecraft.class_291.method_34427(class_291.java:121)
	at net.minecraft.class_286.method_43438(class_286.java:33)
	at net.minecraft.class_286.method_43433(class_286.java:26)
	at net.minecraft.class_1921.method_23012(class_1921.java:751)
	at net.minecraft.class_4597$class_4598.method_22994(class_4597.java:96)
	at net.minecraft.class_4597$class_4598.method_22993(class_4597.java:79)
	at net.minecraft.class_918.method_4021(class_918.java:308)
	at net.minecraft.class_918.method_4010(class_918.java:278)
	at com.simibubi.create.foundation.config.ui.OpenCreateMenuButton.method_25353(OpenCreateMenuButton.java:33)
	at net.minecraft.class_339.method_25359(class_339.java:93)
	at net.minecraft.class_4185.method_25359(class_4185.java:48)
	at net.minecraft.class_339.method_25394(class_339.java:66)
	at net.minecraft.class_437.method_25394(class_437.java:107)
	at net.minecraft.class_442.method_25394(class_442.java:333)
	at net.minecraft.class_425.method_25394(class_425.java:90)
	at net.minecraft.class_757.method_3192(class_757.java:870)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_291.method_34431(class_291.java:128)
	at net.minecraft.class_291.method_34427(class_291.java:121)
	at net.minecraft.class_286.method_43438(class_286.java:33)
	at net.minecraft.class_286.method_43433(class_286.java:26)
	at net.minecraft.class_1921.method_23012(class_1921.java:751)
	at net.minecraft.class_4597$class_4598.method_22994(class_4597.java:96)
	at net.minecraft.class_4597$class_4598.method_22993(class_4597.java:79)
	at net.minecraft.class_918.method_4021(class_918.java:308)
	at net.minecraft.class_918.method_4010(class_918.java:278)
	at com.simibubi.create.foundation.config.ui.OpenCreateMenuButton.method_25353(OpenCreateMenuButton.java:33)
	at net.minecraft.class_339.method_25359(class_339.java:93)
	at net.minecraft.class_4185.method_25359(class_4185.java:48)
	at net.minecraft.class_339.method_25394(class_339.java:66)
	at net.minecraft.class_437.method_25394(class_437.java:107)
	at net.minecraft.class_442.method_25394(class_442.java:333)
	at net.minecraft.class_425.method_25394(class_425.java:90)

-- Overlay render details --
Details:
	Overlay name: net.minecraft.class_425
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:870)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: Default, Fabric Mods, Theinar Language, Everycomp Generated Pack, Immersive Weathering Generated Pack, Supplementaries Generated Pack
	Recovery: Yes
	Recovery reason: java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Multiple entries with same key: minecraft:sign/azalea#main=net.minecraft.class_5607@4ff37650 and minecraft:sign/azalea#main=net.minecraft.class_5607@4ff37650
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:791)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_4014.method_18365(class_4014.java:69)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.class_1255.method_5383(class_1255.java:116)
	at net.minecraft.class_310.method_1523(class_310.java:1129)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: minecraft:sign/azalea#main=net.minecraft.class_5607@4ff37650 and minecraft:sign/azalea#main=net.minecraft.class_5607@4ff37650
	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:376)
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:370)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:153)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:115)
	at com.google.common.collect.ImmutableMap$Builder.buildOrThrow(ImmutableMap.java:574)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:538)
	at net.minecraft.class_5600.method_32073(class_5600.java:297)
	at net.minecraft.class_5599.method_14491(class_5599.java:24)
	at net.minecraft.class_4013.method_29490(class_4013.java:15)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
	... 13 more

Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2348)
	at net.minecraft.class_310.method_1514(class_310.java:787)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by TropheusJ** [comment]
The entire log is needed.

**Comment by TropheusJ** [comment]
closing for inactivity
