### ISSUE TITLE
ClassCastException crash with Starlight

### ISSUE THREAD

**Issue by mosharky** [Fabricators-of-Create/Create#65]
### Describe the Bug

Pondering any item crashes the client. I believe this is due to an incompatibility with Starlight:
```
Caused by: java.lang.ClassCastException: class com.jozufozu.flywheel.core.virtual.VirtualEmptyBlockGetter cannot be cast to class net.minecraft.class_1937 (com.jozufozu.flywheel.core.virtual.VirtualEmptyBlockGetter and net.minecraft.class_1937 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @35f26e72)
	at ca.spottedleaf.starlight.common.light.StarLightInterface.<init>(StarLightInterface.java:62)
	at net.minecraft.world.chunk.light.LightingProvider.handler$fni000$construct(LightingProvider:60)
	at net.minecraft.world.chunk.light.LightingProvider.<init>(LightingProvider:28)
	at com.jozufozu.flywheel.core.virtual.VirtualEmptyBlockGetter$2.<init>(VirtualEmptyBlockGetter.java:38)
	at com.jozufozu.flywheel.core.virtual.VirtualEmptyBlockGetter.<init>(VirtualEmptyBlockGetter.java:28)
	at com.jozufozu.flywheel.core.virtual.VirtualEmptyBlockGetter.<clinit>(VirtualEmptyBlockGetter.java:26)
	... 40 more
```
Would like to also mention that v0.4b isn't in the list of "Mod Versions", so I put 0.4.0a

### Reproduction Steps

1. Ponder Large Cogwheel
2. Instant crash

### Expected Result

To be able to ponder the item/block successfully w/o crashing

### Crash Report or Log

https://pastebin.com/XnhzzuLj

### Operating System

Windows 10

### Mod Version

0.4.0a

### Minecraft Version

1.18.1

### Other Mods

Starlight (and many other mods listed in the crash log)

**Comment by AeiouEnigma** [comment]
Create won't be compatible with Starlight unless and until Spottedleaf implements [a fix](https://github.com/PaperMC/Starlight/pull/111) for the ClassCastException issue you've run into here.

In the meantime, you can [try downloading my forked version of Starlight](https://github.com/AeiouEnigma/Starlight/releases/tag/create_compatibility), which implements the above-linked fix.

**Comment by AeiouEnigma** [comment]
Will be fixed in the next release of Starlight

**Comment by AeiouEnigma** [comment]
Closing this now, since Starlight 1.0.1 was released with the relevant fix.
