### ISSUE TITLE
There are compatibility issues between Create, EMI, and Farmer's Delight

### ISSUE THREAD

**Issue by Chikage0o0** [Fabricators-of-Create/Create#660]
### Describe the Bug

Adding Farmer's Delight when both Create and EMI are loaded will cause EMI to fail to load some of Create's recipes

### Reproduction Steps

1.Add mod Create 、Farmer's Delight and EMI 
2.Join a World
3.
...

### Expected Result

[19:53:41] [Thread-12/ERROR]: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base
[19:53:41] [Thread-12/ERROR]: jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base
[19:53:41] [Thread-12/ERROR]: jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base
[19:53:41] [Thread-12/ERROR]: jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base
[19:53:41] [Thread-12/ERROR]: java.util.Objects.checkIndex(Objects.java:359)
	at java.base
[19:53:41] [Thread-12/ERROR]: java.util.ArrayList.get(ArrayList.java:427)
	at com.simibubi.create.compat.emi.recipes.SpoutEmiRecipe.<init>(SpoutEmiRecipe.java:19)
	at com.simibubi.create.compat.emi.CreateEmiPlugin.addAll(CreateEmiPlugin.java:283)
	at com.simibubi.create.compat.emi.CreateEmiPlugin.register(CreateEmiPlugin.java:269)
	at dev.emi.emi.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:112)
	at java.base
[19:53:41] [Thread-12/ERROR]: java.lang.Thread.run(Thread.java:833)

### Operating System

Windows 11

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

	- create 0.5.0g-796+1.19.2
	- farmersdelight 1.19.2-1.3.9
	- emi 0.5.0+1.19.2
	- fabric-api 0.68.0+1.19.2

**Comment by Chikage0o0** [comment]
https://github.com/newhoryzon/farmers-delight-fabric/issues/115

**Comment by LemmaEOF** [comment]
I found the bug! It's the Farmer's Delight Create-compat [chocolate pie filling recipe](https://github.com/newhoryzon/farmers-delight-fabric/blob/master/src/main/resources/data/farmersdelight/recipes/create/filling/chocolate_pie.json) - the fluid tag `c:chocolates` isn't used in Create, it's `c:chocolate` instead, so switching to the proper tag should stop it from getting index out-of-bounds issues!
