### ISSUE TITLE
Recipes fail to load when using BYG and other mods

### ISSUE THREAD

**Issue by briansemrau** [Fabricators-of-Create/Create#674]
### Describe the Bug

Everything works fine when using Create, BYG (Oh The Biomes You'll Go), and all the other mods listed below before installing JourneyMap. For some reason adding JourneyMap causes this issue to arise, but that could just be coincidence. (I'm not sure how fabric/quilt mod loading order works).

The world loads fine, but some recipes (e.g. andesite alloy) are incorrect.

See analysis / possible fix below.

### Reproduction Steps

n/a

### Expected Result

Recipes should load correctly

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/6376721/206882791-73365f1b-99d7-4987-bc75-ac365c1f8007.png)

### Crash Report or Log

https://gist.github.com/briansemrau/59d776520d6588a27d50012881bf2fe7

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

Architectury
BetterF3
Bookshelf
Collective (Fabric)
Create
EnchantmentDescriptions
Fabric API
Freecam
Indium
Iris
Jade
Journeymap
Lithium
MaLiLib
MiniHUD
Mod Menu
Oh The Biomes You'll Go
Passive Endermen (Fabric)
Phosphor
Roughly Enough Items
Scaffolding Drops Nearby (Fabric)
Sodium
TerraBlender
Textile Backup

### Additional Context

Looking at the logs, it appears that there is an outdated compat recipe:
https://github.com/Fabricators-of-Create/Create/blob/88afd924f068cef53eb438dec648daf360969204/src/generated/resources/data/create/recipes/cutting/compat/byg/mangrove_log.json#L13-L19

```java
[20:51:35] [Render thread/ERROR]: Parsing error loading recipe create:cutting/compat/byg/mangrove_log
com.google.gson.JsonSyntaxException: Unknown item 'byg:mangrove_log'
	at net.minecraft.class_1869.method_17878(class_1869.java:253) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_1869.method_8155(class_1869.java:253) ~[client-intermediary.jar:?]
	at net.minecraft.class_1856.method_8107(class_1856.java:162) ~[client-intermediary.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:579) ~[client-intermediary.jar:?]
	at com.simibubi.create.content.contraptions.processing.ProcessingRecipeSerializer.readFromJson(ProcessingRecipeSerializer.java:66) ~[create-fabric-0.5.0g-7961.19.2.jar.i0:0/:?]
	at com.simibubi.create.content.contraptions.processing.ProcessingRecipeSerializer.fromJson(ProcessingRecipeSerializer.java:154) ~[create-fabric-0.5.0g-7961.19.2.jar.i0:0/:?]
	at com.simibubi.create.content.contraptions.processing.ProcessingRecipeSerializer.method_8121(ProcessingRecipeSerializer.java:21) ~[create-fabric-0.5.0g-7961.19.2.jar.i0:0/:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:135) ~[client-intermediary.jar:?]
```

It looks like BYG renamed `mangrove` to `white_mangrove`:
https://github.com/AOCAWOL/BYG/blob/90ecd7f76738f24b89e86900c23d598fd8ab7e2c/Common/src/main/java/potionstudios/byg/common/block/BYGWoodTypes.java#L88-L91

https://github.com/AOCAWOL/BYG/commit/8785c8a3bbdad746036f289b39d2d702ef787e1b

Obviously this can be fixed by simply updating this compat recipe, but it would make sense to future proof Create by printing a readable error in these cases.

**Comment by briansemrau** [comment]
Issue appears to be fixed locally by modifying the .jar

find: `mangrove`
replace with: `white_mangrove`
in folders: `recipes/**/compat/byg`

**Comment by brianwinterpixel** [comment]
On further testing, this seems to be two separate issues. I'll close this and resubmit them separately.

**Comment by briansemrau** [comment]
After further testing, this appears to be two separate issues. I'll resubmit them separately.
