### ISSUE TITLE
Ticking Entity - Chute

### ISSUE THREAD

**Issue by FlashyCoderDude** [Fabricators-of-Create/Create#717]
I was playing on my Fabric server today and had a situation where my factory was spewing out items because I had a bad logic circuit designed.  I stopped the issue and was putting back the items into my vault using a chute and the server crashed.  I now cannot get logged back into the server because when I get on, I get this error message:

```
 cat crash-2022-12-28_17.13.18-server.txt
---- Minecraft Crash Report ----
// There are four lights!

Time: 2022-12-28 17:13:18
Description: Ticking block entity

java.lang.IllegalArgumentException: Transfer variant may not be blank.
        at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notBlank(StoragePreconditions.java:39)
        at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notBlankNotNegative(StoragePreconditions.java:58)
        at net.fabricmc.fabric.api.transfer.v1.storage.base.SingleVariantStorage.insert(SingleVariantStorage.java:84)
        at com.simibubi.create.content.logistics.block.chute.ChuteItemHandler.insert(ChuteItemHandler.java:27)
        at com.simibubi.create.content.logistics.block.chute.ChuteItemHandler.insert(ChuteItemHandler.java:9)
        at com.simibubi.create.content.contraptions.processing.BasinTileEntity.tryClearingSpoutputOverflow(BasinTileEntity.java:407)
        at com.simibubi.create.content.contraptions.processing.BasinTileEntity.tick(BasinTileEntity.java:348)
        at com.simibubi.create.foundation.tileEntity.SmartTileEntityTicker.tick(SmartTileEntityTicker.java:15)
        at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:660)
        at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:714)
        at net.minecraft.class_1937.method_18471(class_1937.java:456)
        at net.minecraft.class_3218.method_18765(class_3218.java:376)
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
        at net.minecraft.class_3176.method_3813(class_3176.java:289)
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
        at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
        at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notBlank(StoragePreconditions.java:39)
        at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notBlankNotNegative(StoragePreconditions.java:58)
        at net.fabricmc.fabric.api.transfer.v1.storage.base.SingleVariantStorage.insert(SingleVariantStorage.java:84)
        at com.simibubi.create.content.logistics.block.chute.ChuteItemHandler.insert(ChuteItemHandler.java:27)
        at com.simibubi.create.content.logistics.block.chute.ChuteItemHandler.insert(ChuteItemHandler.java:9)
        at com.simibubi.create.content.contraptions.processing.BasinTileEntity.tryClearingSpoutputOverflow(BasinTileEntity.java:407)
        at com.simibubi.create.content.contraptions.processing.BasinTileEntity.tick(BasinTileEntity.java:348)
        at com.simibubi.create.foundation.tileEntity.SmartTileEntityTicker.tick(SmartTileEntityTicker.java:15)
        at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:660)
        at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:714)
        at net.minecraft.class_1937.method_18471(class_1937.java:456)
        at net.minecraft.class_3218.method_18765(class_3218.java:376)

-- Block entity being ticked --
Details:
        Name: create:basin // com.simibubi.create.content.contraptions.processing.BasinTileEntity
        Block: Block{create:basin}[facing=west]
        Block location: World: (1309,67,-2), Section: (at 13,3,14 in 81,4,-1; chunk contains blocks 1296,-64,-16 to 1311,319,-1), Region: (2,-1; contains chunks 64,-32 to 95,-1, blocks 1024,-64,-512 to 1535,319,-1)
        Block: Block{create:basin}[facing=west]
        Block location: World: (1309,67,-2), Section: (at 13,3,14 in 81,4,-1; chunk contains blocks 1296,-64,-16 to 1311,319,-1), Region: (2,-1; contains chunks 64,-32 to 95,-1, blocks 1024,-64,-512 to 1535,319,-1)
Stacktrace:
        at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:660)
        at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:714)
        at net.minecraft.class_1937.method_18471(class_1937.java:456)
        at net.minecraft.class_3218.method_18765(class_3218.java:376)
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
        at net.minecraft.class_3176.method_3813(class_3176.java:289)
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
        at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
        All players: 1 total; [class_3222['Morphius'/13, l='ServerLevel[world]', x=1312.30, y=65.77, z=-2.38]]
        Chunk stats: 3169
        Level dimension: minecraft:overworld
        Level spawn location: World: (-16,64,-48), Section: (at 0,0,0 in -1,4,-3; chunk contains blocks -16,-64,-48 to -1,319,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
        Level time: 63172816 game time, 14720651 day time
        Level name: world
        Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
        Level weather: Rain time: 142372 (now: false), thunder time: 83877 (now: false)
        Known server brands: fabric
        Level was modded: true
        Level storage version: 0x04ABD - Anvil
Stacktrace:
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
        at net.minecraft.class_3176.method_3813(class_3176.java:289)
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
        at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
        Minecraft Version: 1.19.2
        Minecraft Version ID: 1.19.2
        Operating System: Linux (amd64) version 4.15.0-189-generic
        Java Version: 17.0.1, Eclipse Adoptium
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
        Memory: 2736876552 bytes (2610 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
        CPUs: 12
        Processor Vendor: GenuineIntel
        Processor Name: Intel(R) Xeon(R) CPU           X5675  @ 3.07GHz
        Identifier: Intel64 Family 6 Model 44 Stepping 2
        Microarchitecture: Westmere (Server)
        Frequency (GHz): 3.07
        Number of physical packages: 2
        Number of physical CPUs: 12
        Number of logical CPUs: 12
        Graphics card #0 name: unknown
        Graphics card #0 vendor: unknown
        Graphics card #0 VRAM (MB): 0.00
        Graphics card #0 deviceId: unknown
        Graphics card #0 versionInfo: unknown
        Virtual memory max (MB): 12105.29
        Virtual memory used (MB): 5774.24
        Swap memory total (MB): 4096.00
        Swap memory used (MB): 4.31
        JVM Flags: 2 total; -Xmx4G -Xms4G
        Fabric Mods:
                amethystequipment: Amethyst Equipment 1.0.6
                appleskin: AppleSkin 2.4.1+mc1.19
                architectury: Architectury 6.4.62
                badpackets: Bad Packets 0.2.1
                balm-fabric: Balm 4.5.2+0
                bclib: BCLib 2.1.5
                betteranimalsplus: Better Animals Plus 1.19-11.0.7
                betterdeserttemples: YUNG's Better Desert Temples 1.19.2-Fabric-2.2.1
                betterdungeons: YUNG's Better Dungeons 1.19.2-Fabric-3.2.1
                betterend: Better End 2.1.2
                bettermineshafts: YUNG's Better Mineshafts 1.19.2-Fabric-3.2.0
                betternether: Better Nether 7.1.2
                betteroceanmonuments: YUNG's Better Ocean Monuments 1.19.2-Fabric-2.1.0
                betterstrongholds: YUNG's Better Strongholds 1.19.2-Fabric-3.2.0
                bettervillage: Better village 2.0.0
                bookshelf: Bookshelf 16.1.11
                byg: Oh The Biomes You'll Go 2.0.0.13
                        com_electronwill_night-config_core: core 3.6.6
                        com_electronwill_night-config_toml: toml 3.6.6
                cloth-config: Cloth Config v8 8.2.88
                        cloth-basic-math: cloth-basic-math 0.6.1
                comforts: Comforts 6.0.3+1.19.2
                        cardinal-components-entity: Cardinal Components API (entities) 5.0.1
                        spectrelib: SpectreLib 0.10.0+1.19
                cookingforblockheads: Cooking for Blockheads 13.3.0
                create: Create 0.5.0f-776
                        com_google_code_findbugs_jsr305: jsr305 3.0.2
                        fake-player-api: Fake Player API 0.5.0
                        forgeconfigapiport: Forge Config API Port 4.2.6
                        milk: Milk Lib 1.0.50
                                dripstone_fluid_lib: Dripstone Fluid Lib 2.0.1
                        porting_lib: Porting Lib 2.0.612+1.19.2
                                porting_lib_base: Porting Lib Base 2.0.612+1.19.2
                                        mm: Manningham Mills 2.3
                                        serialization_hooks: Serialization Hooks 0.3.26
                                porting_lib_entity: Porting Lib Entity 2.0.612+1.19.2
                                porting_lib_lazy_registration: Porting Lib Lazy Register 2.0.612+1.19.2
                                porting_lib_model_generators: Porting Lib Model Generators 2.0.612+1.19.2
                                porting_lib_models: Porting Lib Models 2.0.612+1.19.2
                                porting_lib_networking: Porting Lib Networking 2.0.612+1.19.2
                                porting_lib_obj_loader: Porting Lib Obj Loader 2.0.612+1.19.2
                                        porting_lib_model_loader: Porting Lib Model Loader 2.0.612+1.19.2
                                porting_lib_tags: Porting Lib Tags 2.0.612+1.19.2
                                porting_lib_transfer: Porting Lib Transfer 2.0.612+1.19.2
                                        porting_lib_extensions: Porting Lib Extensions 2.0.612+1.19.2
                                                porting_lib_accessors: Porting Lib Accessors 2.0.612+1.19.2
                                                porting_lib_attributes: Porting Lib Attributes 2.0.612+1.19.2
                                                        porting_lib_constants: Porting Lib Constants 2.0.612+1.19.2
                                                porting_lib_common: Porting Lib Common 2.0.612+1.19.2
                        reach-entity-attributes: Reach Entity Attributes 2.3.0
                        registrate-fabric: Registrate for Fabric 1.1.42-MC1.19.2
                decorative_blocks: Decorative Blocks 3.0.0
                emerald_tools: Emerald Tools 1.4.38
                        pugh_tools: Pugh Tools 1.3.23
                explorerscompass: Explorer's Compass 1.19.2-2.2.0-fabric
                fabric-api: Fabric API 0.69.0+1.19.2
                        fabric-api-base: Fabric API Base 0.4.13+0d0f210290
                        fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.12+93d8cb8290
                        fabric-biome-api-v1: Fabric Biome API (v1) 9.0.20+0d0f210290
                        fabric-block-api-v1: Fabric Block API (v1) 1.0.1+12bfe4ea90
                        fabric-command-api-v1: Fabric Command API (v1) 1.2.13+f71b366f90
                        fabric-command-api-v2: Fabric Command API (v2) 2.1.9+93d8cb8290
                        fabric-commands-v0: Fabric Commands (v0) 0.2.30+df3654b390
                        fabric-containers-v0: Fabric Containers (v0) 0.1.38+df3654b390
                        fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.4+6064db2a90
                        fabric-convention-tags-v1: Fabric Convention Tags 1.2.0+27265b3490
                        fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.7+aeb40ebe90
                        fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.3+ad31814d90
                        fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.33+0d0f210290
                        fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.2+9244241690
                        fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.31+6eb9a2a190
                        fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.31+df3654b390
                        fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.23+c6af733c90
                        fabric-item-api-v1: Fabric Item API (v1) 1.6.1+fa140d5990
                        fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.36+9244241690
                        fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.2+9244241690
                        fabric-loot-api-v2: Fabric Loot API (v2) 1.1.10+83a8659290
                        fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.13+9e7660c690
                        fabric-message-api-v1: Fabric Message API (v1) 5.0.5+93d8cb8290
                        fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.21+33fbc73890
                        fabric-networking-api-v1: Fabric Networking API (v1) 1.2.8+3b1d070f90
                        fabric-networking-v0: Fabric Networking (v0) 0.3.25+df3654b390
                        fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.3+06e0e25190
                        fabric-particles-v1: Fabric Particles (v1) 1.0.12+79adfe0a90
                        fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.29+9244241690
                        fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.17+0d0f210290
                        fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.9+c6af733c90
                        fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.1+aae9039d90
                        fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.2+574a764890
                        fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.4+1cc24b1b90
                        fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.3+9d081d6490
                        fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.2+42d99c3290
                fabricenchantments: Fabric Enchantments 0.9.0
                fabricloader: Fabric Loader 0.14.10
                farmersdelight: Farmer's Delight 1.19.2-1.3.6
                farmersknives: Farmer's Knives 2.3
                fwaystones: Fabric Waystones 3.0.5+mc1.19.2
                geckolib3: Geckolib 3.1.37
                        com_eliotlash_mclib_mclib: mclib 20
                geodes: More Geodes 1.5.2
                graveyard: The Graveyard 2.3
                iceberg: Iceberg 1.0.46
                inmis: Inmis 2.7.1-1.19
                        omega-config: OmegaConfig 1.2.3-1.18.1
                inventorysorter: Inventory Sorter 1.8.10-1.19
                        kyrptconfig: Kyrpt Config 1.4.14-1.19
                java: OpenJDK 64-Bit Server VM 17
                libraryferret: Library ferret 3.0.0
                lithium: Lithium 0.10.4
                lootr: Lootr 0.4.24.63
                mcda: MC Dungeons Armors 2.2.0
                mcdar: MC Dungeons Artifacts 1.5.2-1.19
                mcdw: MC Dungeons Weapons 5.0.4-1.19
                        enchant_giver: Enchant Giver 1.3.0
                minecraft: Minecraft 1.19.2
                mvs: Vanilla Structure Mod 2.5.10-1.19.2
                naturescompass: Nature's Compass 1.19.2-2.1.0-fabric
                noenchantcap: No Enchant Cap 2.2.3
                        com_github_llamalad7_mixinextras: MixinExtras 0.1.1
                owo: oωo 0.8.5+1.19
                        blue_endless_jankson: jankson 1.2.1
                phosphor: Phosphor 0.8.1
                roughlyenoughitems: Roughly Enough Items 9.1.577
                        error_notifier: Error Notifier 1.0.9
                simple_backpack: SimpleBackpack 1.3.25
                takesapillage: Takes a Pillage 1.0.4
                        midnightlib: MidnightLib 1.0.0
                terrablender: TerraBlender 2.0.1.130
                toms_storage: Tom's Simple Storage Mod 1.4.5
                trade_cycling: Trade Cycling 1.19.2-1.0.5
                trinkets: Trinkets 3.4.1
                villagernames: Villager Names 4.0.8
                        cardinal-components-base: Cardinal Components API (base) 5.0.2
                        cardinal-components-level: Cardinal Components API (world saves) 5.0.2
                wabi_sabi_structures: Wabi-Sabi Structures 1.1.2
                wands: Building Wands 2.6.3_release
                wthit: wthit 5.13.4
                xaerominimap: Xaero's Minimap 22.16.2
                xaeroworldmap: Xaero's World Map 1.28.3
                yigd: You're in Grave Danger 1.4.6
                yungsapi: YUNG's API 1.19.2-Fabric-3.8.2
                        org_javassist_javassist: javassist 3.28.0-GA
                        org_reflections_reflections: reflections 0.10.2
        Server Running: true
        Player Count: 1 / 20; [class_3222['Morphius'/13, l='ServerLevel[world]', x=1312.30, y=65.77, z=-2.38]]
        Data Packs: vanilla, Fabric Mods, file/createabunch
        World Generation: Stable
        Is Modded: Definitely; Server brand changed to 'fabric'
        Type: Dedicated Server (map_server.txt)
```

**Comment by TropheusJ** [comment]
this has been fixed, update
