### ISSUE TITLE
Minecraft crashes when I try to kill an entity. 1.19.2 bug

### ISSUE THREAD

**Issue by HateAndLoveModding** [Fabricators-of-Create/Create#841]
Here is the error. 
Description: Unexpected error

java.lang.NoSuchFieldError: ATTACK_KNOCKBACK
        at net.minecraft.entity.player.PlayerEntity.attack(PlayerEntity.java:1235)
        at net.minecraft.client.network.ClientPlayerInteractionManager.attackEntity(ClientPlayerInteractionManager.java:412)
        at net.minecraft.client.MinecraftClient.doAttack(MinecraftClient.java:1678)
        at net.minecraft.client.MinecraftClient.handleInputEvents(MinecraftClient.java:1999)
        at net.minecraft.client.MinecraftClient.tick(MinecraftClient.java:1829)
        at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1135)
        at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:768)
        at net.minecraft.client.main.Main.main(Main.java:244)
        at net.minecraft.client.main.Main.main(Main.java:51)
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
        at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
        at net.minecraft.entity.player.PlayerEntity.attack(PlayerEntity.java:1235)
        at net.minecraft.client.network.ClientPlayerInteractionManager.attackEntity(ClientPlayerInteractionManager.java:412)
        at net.minecraft.client.MinecraftClient.doAttack(MinecraftClient.java:1678)
        at net.minecraft.client.MinecraftClient.handleInputEvents(MinecraftClient.java:1999)

-- Affected level --
Details:
        All players: 1 total; [ClientPlayerEntity['Ryker'/9, l='ClientLevel', x=-861.59, y=68.63, z=-1468.98]]
        Chunk stats: 2809, 419
        Level dimension: minecraft:overworld
        Level spawn location: World: (-720,77,-704), Section: (at 0,13,0 in -45,4,-44; chunk contains blocks -720,-64,-704 to -705,319,-689), Region: (-2,-2; contains chunks -64,-64 to -33,-33, blocks -1024,-64,-1024 to -513,319,-513)
        Level time: 145733 game time, 9019 day time
        Server brand: fabric
        Server type: Integrated singleplayer server
Stacktrace:
        at net.minecraft.client.world.ClientWorld.addDetailsToCrashReport(ClientWorld.java:453)
        at net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient.java:2341)
        at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:792)
        at net.minecraft.client.main.Main.main(Main.java:244)
        at net.minecraft.client.main.Main.main(Main.java:51)
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
        at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

**Comment by TropheusJ** [comment]
need the full crash log

**Comment by TropheusJ** [comment]
Please try with the latest release

**Comment by TropheusJ** [comment]
closing for inactivity

**Comment by FrostBird347** [comment]
I can confirm that I am also experiencing this bug in the latest 1.19.2 version.

The mods present don't seem to matter and this bug instead only occurs for me when launching the game through visual studio code, with create installed.
