### ISSUE TITLE
Incompatibility with optifabric (Fabric)

### ISSUE THREAD

**Issue by chuckarrow** [Fabricators-of-Create/Create#882]
### Describe the Bug

Error on Startup when using optifabric
`[17:00:32] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.19
[17:00:32] [ForkJoinPool-1-worker-3/WARN]: Mod create uses the version 0.5.0.i-991+1.19.2 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'i'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[17:00:32] [ForkJoinPool-1-worker-8/WARN]: Mod flywheel uses the version 0.6.8.a-4 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'a'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[17:00:32] [main/WARN]: Mod resolution failed
[17:00:32] [main/INFO]: Immediate reason: [NEG_HARD_DEP create 0.5.0.i-991+1.19.2 {breaks optifabric @ [*]}, ROOT_FORCELOAD_SINGLE create 0.5.0.i-991+1.19.2, ROOT_FORCELOAD_SINGLE optifabric 1.13.16]
[17:00:32] [main/INFO]: Reason: [NEG_HARD_DEP create 0.5.0.i-991+1.19.2 {breaks optifabric @ [*]}]
[17:00:32] [main/INFO]: Fix: add [], remove [], replace [[create 0.5.0.i-991+1.19.2] -> add:create 1 ([(-?,?)])]
[17:00:32] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Create' (create) 0.5.0.i-991+1.19.2 with any version that is compatible with:
		 - optifabric 1.13.16
Unmet dependency listing:
	 - Mod 'Create' (create) 0.5.0.i-991+1.19.2 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.16!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.19.jar:?]
`

### Reproduction Steps

1. Run game with optifabric with fabric
2.
3.
...

### Expected Result

`[17:00:32] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.19
[17:00:32] [ForkJoinPool-1-worker-3/WARN]: Mod create uses the version 0.5.0.i-991+1.19.2 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'i'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[17:00:32] [ForkJoinPool-1-worker-8/WARN]: Mod flywheel uses the version 0.6.8.a-4 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'a'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[17:00:32] [main/WARN]: Mod resolution failed
[17:00:32] [main/INFO]: Immediate reason: [NEG_HARD_DEP create 0.5.0.i-991+1.19.2 {breaks optifabric @ [*]}, ROOT_FORCELOAD_SINGLE create 0.5.0.i-991+1.19.2, ROOT_FORCELOAD_SINGLE optifabric 1.13.16]
[17:00:32] [main/INFO]: Reason: [NEG_HARD_DEP create 0.5.0.i-991+1.19.2 {breaks optifabric @ [*]}]
[17:00:32] [main/INFO]: Fix: add [], remove [], replace [[create 0.5.0.i-991+1.19.2] -> add:create 1 ([(-?,?)])]
[17:00:32] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Create' (create) 0.5.0.i-991+1.19.2 with any version that is compatible with:
		 - optifabric 1.13.16
Unmet dependency listing:
	 - Mod 'Create' (create) 0.5.0.i-991+1.19.2 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.16!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.19.jar:?]
`

### Operating System

Win 11

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

Optifabric

**Comment by TropheusJ** [comment]
Correct

**Comment by chuckarrow** [comment]
may i ask why?

**Comment by TropheusJ** [comment]
Causes problems, compatibility is too difficult, alternatives are available on fabric

**Comment by DarianLStephens** [comment]
Basically, just use Iris.
