### ISSUE TITLE
potato cannon insta crash

### ISSUE THREAD

**Issue by Flizshynt** [Fabricators-of-Create/Create#891]
### Describe the Bug

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2023-04-16 02:05:01
Description: Unexpected error

org.spongepowered.asm.mixin.injection.callback.CancellationException: The call method_6104 is not cancellable.
    at org.spongepowered.asm.mixin.injection.callback.CallbackInfo.cancel(CallbackInfo.java:101)
    at net.minecraft.class_1309.handler$fjf000$swing(class_1309.java:28677)
    at net.minecraft.class_1309.method_6104(class_1309.java)
    at net.minecraft.class_746.method_6104(class_746.java:405)
    at net.minecraft.class_310.method_1583(class_310.java:1771)
    at net.minecraft.class_310.method_1508(class_310.java:2002)
    at net.minecraft.class_310.method_1574(class_310.java:1829)
    at net.minecraft.class_310.method_1523(class_310.java:1135)
    at net.minecraft.class_310.method_1514(class_310.java:768)
    at net.minecraft.client.main.Main.method_44604(Main.java:244)
    at net.minecraft.client.main.Main.main(Main.java:51)
    at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### Reproduction Steps

1.shoot potato
2.
3.
...

### Expected Result

if i shoot the potato cannon the game crashes.

### Operating System

windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

[Wibileedoo-0.5.1i.zip](https://github.com/Fabricators-of-Create/Create/files/11241016/Wibileedoo-0.5.1i.zip)

**Comment by TropheusJ** [comment]
update your fabric loader to 0.14.15 or newer and get a new crash log.

**Comment by TropheusJ** [comment]
closing for inactivity. This is not a Create issue, but some other mod with a broken and unlabeled `swing` injector.
