### ISSUE TITLE
Create all train data dissapearing when updating the mod

### ISSUE THREAD

**Issue by alf1e** [Fabricators-of-Create/Create#985]
### Describe the Bug

Hello. When I updated my mod to `create-fabric-0.5.1-b-build.1079mc1.19.2.jar` I tried to load my server (It has a lot of trains) and it errored  with this
```
[20:03:04] [Server thread/ERROR]: Error loading saved data: create_tracks
java.lang.ClassCastException: class net.minecraft.class_2189 cannot be cast to class com.simibubi.create.content.trains.bogey.AbstractBogeyBlock (net.minecraft.class_2189 and com.simibubi.create.content.trains.bogey.AbstractBogeyBlock are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @548a9f61)
    at com.simibubi.create.content.trains.entity.CarriageBogey.read(CarriageBogey.java:194) ~[create-fabric-0.5.1-b-build.1079+mc1.19.2.jar:?]
    at com.simibubi.create.content.trains.entity.Carriage.read(Carriage.java:487) ~[create-fabric-0.5.1-b-build.1079+mc1.19.2.jar:?]
    at com.simibubi.create.content.trains.entity.Train.lambda$read$28(Train.java:1150) ~[create-fabric-0.5.1-b-build.1079+mc1.19.2.jar:?]
    at com.simibubi.create.foundation.utility.NBTHelper.lambda$iterateCompoundList$2(NBTHelper.java:65) ~[create-fabric-0.5.1-b-build.1079+mc1.19.2.jar:?]
    at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
    at com.simibubi.create.foundation.utility.NBTHelper.iterateCompoundList(NBTHelper.java:65) ~[create-fabric-0.5.1-b-build.1079+mc1.19.2.jar:?]
    at com.simibubi.create.content.trains.entity.Train.read(Train.java:1149) ~[create-fabric-0.5.1-b-build.1079+mc1.19.2.jar:?]
    at com.simibubi.create.content.trains.RailwaySavedData.lambda$load$5(RailwaySavedData.java:60) ~[create-fabric-0.5.1-b-build.1079+mc1.19.2.jar:?]
    at com.simibubi.create.foundation.utility.NBTHelper.lambda$iterateCompoundList$2(NBTHelper.java:65) ~[create-fabric-0.5.1-b-build.1079+mc1.19.2.jar:?]
    at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
    at com.simibubi.create.foundation.utility.NBTHelper.iterateCompoundList(NBTHelper.java:65) ~[create-fabric-0.5.1-b-build.1079+mc1.19.2.jar:?]
    at com.simibubi.create.content.trains.RailwaySavedData.load(RailwaySavedData.java:59) ~[create-fabric-0.5.1-b-build.1079+mc1.19.2.jar:?]
    at net.minecraft.class_26.method_120(class_26.java:72) ~[server-intermediary.jar:?]
    at net.minecraft.class_26.method_20786(class_26.java:59) ~[server-intermediary.jar:?]
    at net.minecraft.class_26.method_17924(class_26.java:43) ~[server-intermediary.jar:?]
    at com.simibubi.create.content.trains.RailwaySavedData.load(RailwaySavedData.java:99) ~[create-fabric-0.5.1-b-build.1079+mc1.19.2.jar:?]
    at com.simibubi.create.content.trains.GlobalRailwayManager.loadTrackData(GlobalRailwayManager.java:89) ~[create-fabric-0.5.1-b-build.1079+mc1.19.2.jar:?]
    at com.simibubi.create.content.trains.GlobalRailwayManager.levelLoaded(GlobalRailwayManager.java:83) ~[create-fabric-0.5.1-b-build.1079+mc1.19.2.jar:?]
    at com.simibubi.create.foundation.events.CommonEvents.onLoadWorld(CommonEvents.java:172) ~[create-fabric-0.5.1-b-build.1079+mc1.19.2.jar:?]
    at net.fabricmc.fabric.api.event.lifecycle.v1.ServerWorldEvents.lambda$static$0(ServerWorldEvents.java:34) ~[fabric-lifecycle-events-v1-2.2.4+1b46dc7890-db0fd3f5dc0d6099.jar:?]
    at net.minecraft.server.MinecraftServer.redirect$zid000$fabric-lifecycle-events-v1$onLoadWorld(MinecraftServer.java:3329) ~[server-intermediary.jar:?]
    at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:351) ~[server-intermediary.jar:?]
    at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:315) ~[server-intermediary.jar:?]
    at net.minecraft.class_3176.method_3823(class_3176.java:172) ~[server-intermediary.jar:?]
    at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:636) ~[server-intermediary.jar:?]
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
    at java.lang.Thread.run(Thread.java:833) [?:?]
```
No trains will load, cannot place station on tracks and signals do not work, nor stations.

Please help!

### Reproduction Steps

1. Install Create Steam 'n' Rails mod
2. Have a few trains
3. Update mod from 0.5 to 0.5.1
4. Watch everything vanish
...

### Expected Result

Actually have the trains instead of them ceising to exist.

### Operating System

Linux (Client) Linux (Server

### Mod Version

0.5.1b

### Minecraft Version

1.19.2

### Other Mods

Create Steam 'n' Rails
World Edit

**Comment by Boxersteavee** [comment]
Thing to note: It is on fabric. (Me and Alfie both manage the server)

**Comment by Boxersteavee** [comment]
[world.zip](https://github.com/Fabricators-of-Create/Create/files/11928917/world.zip)
Here is the world in question, in-case you find it difficult to reproduce in your own world.

**Comment by TropheusJ** [comment]
It seems your bogeys do not have type data specified. I've added a fallback, so it won't crash, but broken bogeys will become default ones.
